<template>
  <div class="space-y-4 px-4 md:px-6">
    <AnalyticsAcademicFilterBar :filters="filters" :terms="terms" :class-options="classOptions"
      :subject-options="subjectOptions" :level-options="levelOptions" :class-loading="classStore.loading"
      :subject-loading="subjectStore.loading" />

    <AnalyticsAcademicTabNav :query="queryString" />

    <UCard v-if="!filters.termId">
      <div class="flex flex-col items-center justify-center py-14 text-center">
        <UIcon name="i-lucide-graduation-cap" class="mb-3 size-10 text-muted" />
        <p class="text-sm font-medium text-highlighted">Select a term to generate a report.</p>
      </div>
    </UCard>

    <div v-else class="space-y-4">
      <UCard :ui="{ body: 'p-0 sm:p-0' }">
        <UTable :data="students" :columns="studentColumns" :loading="loadingReport" class="hidden md:block">
          <template #empty-state>
            <div class="flex flex-col items-center gap-2 py-10">
              <UIcon name="i-lucide-users" class="text-4xl text-gray-400" />
              <p class="text-gray-500">No approved scores for this selection yet.</p>
            </div>
          </template>
          <template #loading>
            <TableLoading :size="studentColumns.length" />
          </template>
          <template #student-cell="{ row }">
            {{ row.original.givenNames }} {{ row.original.familyName }}
          </template>
          <template #overallAverage-cell="{ row }">{{ row.original.overallAverage }}%</template>
          <template #assessments-cell="{ row }">
            {{ row.original.assessmentsCompleted }} done
            <span v-if="row.original.assessmentsMissing" class="text-error">
              &middot; {{ row.original.assessmentsMissing }} missing
            </span>
          </template>
          <template #actions-cell="{ row }">
            <UButton size="xs" variant="soft" icon="i-lucide-line-chart" @click="openTrend(row.original)">
              Trend
            </UButton>
          </template>
        </UTable>

        <!-- Mobile compact list -->
        <div class="md:hidden">
          <template v-if="loadingReport">
            <div v-for="i in 6" :key="i" class="flex items-center justify-between gap-3 border-b border-default px-4 py-3 last:border-0">
              <div class="flex min-w-0 items-center gap-3">
                <USkeleton class="size-10 shrink-0 rounded-full" />
                <div class="min-w-0 space-y-2">
                  <USkeleton class="h-4 w-32 rounded-md" />
                  <USkeleton class="h-3 w-24 rounded-md" />
                </div>
              </div>
              <USkeleton class="h-6 w-14 shrink-0 rounded-full" />
            </div>
          </template>

          <template v-else-if="students.length">
            <button v-for="s in students" :key="s.enrollmentId" type="button"
              class="flex w-full items-center justify-between gap-3 border-b border-default px-4 py-3 text-left last:border-0 active:bg-muted/50"
              @click="openTrend(s)">
              <div class="flex min-w-0 items-center gap-3">
                <UAvatar size="md" icon="i-lucide-user-round" :alt="`${s.givenNames} ${s.familyName}`" />
                <div class="min-w-0">
                  <h3 class="truncate text-sm font-semibold text-highlighted">{{ s.givenNames }} {{ s.familyName }}</h3>
                  <p class="truncate text-xs text-muted">
                    {{ s.assessmentsCompleted }} done
                    <span v-if="s.assessmentsMissing" class="text-error">&middot; {{ s.assessmentsMissing }} missing</span>
                  </p>
                </div>
              </div>
              <div class="flex shrink-0 items-center gap-2">
                <UBadge :label="`${s.overallAverage}%`" variant="soft" color="primary" size="sm" />
                <UIcon name="i-lucide-line-chart" class="text-muted" />
              </div>
            </button>
          </template>

          <template v-else>
            <div class="flex flex-col items-center py-16">
              <UIcon name="i-lucide-users" class="mb-3 size-10 text-muted" />
              <p class="text-sm text-muted">No approved scores for this selection yet.</p>
            </div>
          </template>
        </div>

        <template v-if="students.length" #footer>
          <div class="flex items-center justify-between">
            <Showing :meta="studentsMeta" />
            <UPagination v-model:page="studentPage" size="sm" :page-size="studentPageSize"
              :items-per-page="studentPageSize" :total="report?.studentsTotal ?? 0" show-edges />
          </div>
        </template>
      </UCard>

      <p class="px-2 text-center text-[10px] uppercase tracking-widest text-gray-300">
        Generated by Skultem &middot; {{ generatedDate }}
      </p>
    </div>

    <AnalyticsAcademicTrendModal v-model:open="trendOpen" :student-name="trendStudentName" />
  </div>
</template>

<script setup lang="ts">
const reportStore = useAcademicReportStore()
const { success, error: toastError } = useNotify()
const { filters, terms, classOptions, subjectOptions, levelOptions, queryString, apiFilters, ensureLoaded,
  classStore, subjectStore } = useAcademicReportFilters()

const { report, loadingReport } = storeToRefs(reportStore)
const downloading = ref(false)
const studentPage = ref(1)
const studentPageSize = 20

const students = computed(() => report.value?.students || [])
const termLabel = computed(() => terms.value.find(t => t.value === filters.termId)?.label || '—')
const classLabel = computed(() => classOptions.value.find(c => c.value === filters.classId)?.label || '—')
const subjectLabel = computed(() => subjectOptions.value.find(s => s.value === filters.subjectId)?.label || '')
const generatedDate = computed(() => new Date().toLocaleString())

const studentsMeta = computed(() => useMeta({
  page: report.value?.studentsPage ?? 1,
  size: report.value?.studentsSize ?? studentPageSize,
  count: report.value?.studentsTotal ?? 0
}))

const studentColumns = [
  { id: 'student', header: 'Student' },
  { accessorKey: 'overallAverage', header: 'Overall Average' },
  { id: 'assessments', header: 'Assessments' },
  { id: 'actions', meta: { class: { td: 'text-right' } } }
]

const trendOpen = ref(false)
const trendStudentName = ref('')

function openTrend(student: { enrollmentId: string, givenNames: string, familyName: string }) {
  trendStudentName.value = `${student.givenNames} ${student.familyName}`
  trendOpen.value = true
  reportStore.fetchStudentTrend(student.enrollmentId, filters.termId)
}

function exportStudents() {
  downloadCsv('student-performance', ['Student', 'Overall Average', 'Assessments Completed', 'Assessments Missing'],
    students.value.map(s => [`${s.givenNames} ${s.familyName}`, s.overallAverage, s.assessmentsCompleted, s.assessmentsMissing]))
}

async function loadReport() {
  if (!filters.termId) return
  await reportStore.fetchReport({ ...apiFilters.value, page: studentPage.value, size: studentPageSize })
}

watch(apiFilters, () => {
  studentPage.value = 1
  loadReport()
})
watch(studentPage, loadReport)

async function downloadPdf() {
  downloading.value = true
  try {
    const { $generatePdf } = useNuxtApp()
    await $generatePdf('#academic-report-preview', `academic-report-students-${filters.termId || 'report'}`)
    success('Report downloaded')
  } catch (err: any) {
    toastError(err?.message || 'Failed to generate PDF')
  } finally {
    downloading.value = false
  }
}

onMounted(async () => {
  useAppStore().setTitle('Student Performance')
  document.title = 'Student Performance | Skultem'
  await ensureLoaded()
  await loadReport()
})

definePageMeta({
  role: [Role.ADMIN, Role.OWNER, Role.PROPRIETOR]
})
</script>
