<template>
  <div class="space-y-4 px-4 md:px-6">
    <AnalyticsAcademicFilterBar :filters="filters" :terms="terms" :class-options="classOptions"
      :subject-options="subjectOptions" :level-options="levelOptions" :class-loading="classStore.loading"
      :subject-loading="subjectStore.loading" />

    <AnalyticsAcademicTabNav :query="queryString" />

    <UCard v-if="!filters.termId">
      <div class="flex flex-col items-center justify-center py-14 text-center">
        <UIcon name="i-lucide-graduation-cap" class="mb-3 size-10 text-muted" />
        <p class="text-sm font-medium text-highlighted">Select a term to generate a report.</p>
      </div>
    </UCard>

    <div v-else class="space-y-4">
      <UCard v-if="!loadingReport && subjects.length">
        <template #header>
          <h2 class="font-semibold">Average Score by Subject</h2>
        </template>
        <ClientOnly>
          <ApexChart type="bar" height="280" :options="subjectChartOptions" :series="subjectChartSeries" />
        </ClientOnly>
      </UCard>

      <UCard :ui="{ body: 'p-0 sm:p-0' }">
        <UTable :data="subjects" :columns="subjectColumns" :loading="loadingReport" class="hidden md:block">
          <template #empty-state>
            <div class="flex flex-col items-center gap-2 py-10">
              <UIcon name="i-lucide-book-open" class="text-4xl text-gray-400" />
              <p class="text-gray-500">No approved subject data for this selection yet.</p>
            </div>
          </template>
          <template #loading>
            <TableLoading :size="subjectColumns.length" />
          </template>
          <template #averageScore-cell="{ row }">{{ row.original.averageScore }}%</template>
          <template #medianScore-cell="{ row }">{{ row.original.medianScore }}%</template>
          <template #highestScore-cell="{ row }">{{ row.original.highestScore }}%</template>
          <template #lowestScore-cell="{ row }">{{ row.original.lowestScore }}%</template>
          <template #passRate-cell="{ row }">{{ row.original.passRate }}%</template>
          <template #passFail-cell="{ row }">
            <span class="text-success">{{ row.original.passCount }} pass</span>
            <span class="text-muted"> / </span>
            <span class="text-error">{{ row.original.failCount }} fail</span>
          </template>
          <template #gradeDistribution-cell="{ row }">
            <div class="flex flex-wrap gap-1">
              <UBadge v-for="g in row.original.gradeDistribution" :key="g.grade" size="sm" variant="subtle">
                {{ g.grade }}: {{ g.count }}
              </UBadge>
            </div>
          </template>
        </UTable>

        <!-- Mobile compact list -->
        <div class="md:hidden">
          <template v-if="loadingReport">
            <div v-for="i in 4" :key="i" class="flex items-center justify-between gap-3 border-b border-default px-4 py-3 last:border-0">
              <div class="min-w-0 space-y-2">
                <USkeleton class="h-4 w-32 rounded-md" />
                <USkeleton class="h-3 w-24 rounded-md" />
              </div>
              <USkeleton class="h-6 w-14 shrink-0 rounded-full" />
            </div>
          </template>

          <template v-else-if="subjects.length">
            <button v-for="s in subjects" :key="s.subjectId" type="button"
              class="flex w-full items-center justify-between gap-3 border-b border-default px-4 py-3 text-left last:border-0 active:bg-muted/50"
              @click="openSubject(s)">
              <div class="min-w-0">
                <h3 class="truncate text-sm font-semibold text-highlighted">{{ s.subjectName }}</h3>
                <p class="truncate text-xs text-muted">{{ s.studentsAssessed }} assessed &middot; {{ s.passCount }} pass / {{ s.failCount }} fail</p>
              </div>
              <div class="flex shrink-0 items-center gap-2">
                <UBadge :label="`${s.averageScore}% avg`" variant="soft" color="primary" size="sm" />
                <UIcon name="i-lucide-chevron-right" class="text-muted" />
              </div>
            </button>
          </template>

          <template v-else>
            <div class="flex flex-col items-center py-16">
              <UIcon name="i-lucide-book-open" class="mb-3 size-10 text-muted" />
              <p class="text-sm text-muted">No approved subject data for this selection yet.</p>
            </div>
          </template>
        </div>
      </UCard>

      <p class="px-2 text-center text-[10px] uppercase tracking-widest text-gray-300">
        Generated by Skultem &middot; {{ generatedDate }}
      </p>
    </div>

    <ReportDetailModal v-model:open="detailOpen" :title="selectedSubject?.subjectName || ''" icon="i-lucide-book-open"
      :fields="subjectDetailFields" />
  </div>
</template>

<script setup lang="ts">
const ApexChart = defineAsyncComponent(() => import('vue3-apexcharts'))

const reportStore = useAcademicReportStore()
const { success, error: toastError } = useNotify()
const { filters, terms, classOptions, subjectOptions, levelOptions, queryString, apiFilters, ensureLoaded,
  classStore, subjectStore } = useAcademicReportFilters()

const { report, loadingReport } = storeToRefs(reportStore)
const downloading = ref(false)

const subjects = computed(() => report.value?.subjects || [])
const termLabel = computed(() => terms.value.find(t => t.value === filters.termId)?.label || '—')
const classLabel = computed(() => classOptions.value.find(c => c.value === filters.classId)?.label || '—')
const subjectLabel = computed(() => subjectOptions.value.find(s => s.value === filters.subjectId)?.label || '')
const generatedDate = computed(() => new Date().toLocaleString())

const subjectColumns = [
  { accessorKey: 'subjectName', header: 'Subject' },
  { accessorKey: 'averageScore', header: 'Average' },
  { accessorKey: 'medianScore', header: 'Median' },
  { accessorKey: 'highestScore', header: 'Highest' },
  { accessorKey: 'lowestScore', header: 'Lowest' },
  { accessorKey: 'passRate', header: 'Pass Rate' },
  { accessorKey: 'studentsAssessed', header: 'Assessed' },
  { id: 'passFail', header: 'Pass / Fail' },
  { id: 'gradeDistribution', header: 'Grades' }
]

const subjectChartOptions = computed(() => ({
  chart: { id: 'subject-performance', toolbar: { show: false } },
  xaxis: { categories: subjects.value.map(s => s.subjectName) },
  colors: ['#7b2183'],
  grid: { borderColor: 'var(--app-border)', strokeDashArray: 4 },
  dataLabels: { enabled: true, formatter: (val: number) => `${val}%` },
  yaxis: { max: 100 }
}))

const subjectChartSeries = computed(() => [{
  name: 'Average Score',
  data: subjects.value.map(s => s.averageScore)
}])

const detailOpen = ref(false)
const selectedSubject = ref<typeof subjects.value[number] | null>(null)

function openSubject(subject: typeof subjects.value[number]) {
  selectedSubject.value = subject
  detailOpen.value = true
}

const subjectDetailFields = computed<ReportDetailField[]>(() => {
  const s = selectedSubject.value
  if (!s) return []
  return [
    { label: 'Average', value: `${s.averageScore}%` },
    { label: 'Median', value: `${s.medianScore}%` },
    { label: 'Highest', value: `${s.highestScore}%` },
    { label: 'Lowest', value: `${s.lowestScore}%` },
    { label: 'Pass Rate', value: `${s.passRate}%` },
    { label: 'Students Assessed', value: s.studentsAssessed },
    { label: 'Pass / Fail', value: `${s.passCount} / ${s.failCount}` }
  ]
})

function exportSubjects() {
  downloadCsv('subject-performance', ['Subject', 'Average', 'Median', 'Highest', 'Lowest', 'Pass Rate', 'Assessed', 'Pass', 'Fail'],
    subjects.value.map(s => [s.subjectName, s.averageScore, s.medianScore, s.highestScore, s.lowestScore, s.passRate, s.studentsAssessed, s.passCount, s.failCount]))
}

async function loadReport() {
  if (!filters.termId) return
  await reportStore.fetchReport({ ...apiFilters.value, page: 1, size: 1 })
}

watch(apiFilters, loadReport)

async function downloadPdf() {
  downloading.value = true
  try {
    const { $generatePdf } = useNuxtApp()
    await $generatePdf('#academic-report-preview', `academic-report-subjects-${filters.termId || 'report'}`)
    success('Report downloaded')
  } catch (err: any) {
    toastError(err?.message || 'Failed to generate PDF')
  } finally {
    downloading.value = false
  }
}

onMounted(async () => {
  useAppStore().setTitle('Subject Performance')
  document.title = 'Subject Performance | Skultem'
  await ensureLoaded()
  await loadReport()
})

definePageMeta({
  role: [Role.ADMIN, Role.OWNER, Role.PROPRIETOR]
})
</script>
