<template>
  <div class="space-y-4 px-4 md:px-6">
    <AnalyticsAcademicFilterBar :filters="filters" :terms="terms" :class-options="classOptions"
      :subject-options="subjectOptions" :level-options="levelOptions" :class-loading="classStore.loading"
      :subject-loading="subjectStore.loading" />

    <AnalyticsAcademicTabNav :query="queryString" />

    <UCard v-if="!filters.termId">
      <div class="flex flex-col items-center justify-center py-14 text-center">
        <UIcon name="i-lucide-graduation-cap" class="mb-3 size-10 text-muted" />
        <p class="text-sm font-medium text-highlighted">Select a term to generate a report.</p>
      </div>
    </UCard>

    <div v-else class="space-y-4">
      <UCard>
        <div v-if="loadingAcademicTrend" class="space-y-3">
          <USkeleton class="h-56 w-full" />
        </div>

        <div v-else-if="!academicTrend || academicTrend.points.length < 2" class="py-10 text-center text-sm text-muted">
          Not enough data for a trend yet.
        </div>

        <template v-else>
          <UBadge :color="trendBadge?.color" variant="subtle" class="mb-4">
            Performance trend: {{ trendBadge?.text }}
          </UBadge>
          <ClientOnly>
            <ApexChart type="line" height="300" :options="trendChartOptions" :series="trendChartSeries" />
          </ClientOnly>
        </template>
      </UCard>

      <p class="px-2 text-center text-[10px] uppercase tracking-widest text-gray-300">
        Generated by Skultem &middot; {{ generatedDate }}
      </p>
    </div>
  </div>
</template>

<script setup lang="ts">
const ApexChart = defineAsyncComponent(() => import('vue3-apexcharts'))

const reportStore = useAcademicReportStore()
const { filters, terms, classOptions, subjectOptions, levelOptions, queryString, apiFilters, ensureLoaded,
  classStore, subjectStore } = useAcademicReportFilters()

const { academicTrend, loadingAcademicTrend } = storeToRefs(reportStore)

const generatedDate = computed(() => new Date().toLocaleString())

const trendLabelMap: Record<string, { text: string, color: 'success' | 'error' | 'neutral' | 'warning' }> = {
  IMPROVING: { text: 'Improving', color: 'success' },
  DECLINING: { text: 'Declining', color: 'error' },
  STABLE: { text: 'Stable', color: 'neutral' },
  INSUFFICIENT_DATA: { text: 'Not enough data yet', color: 'warning' }
}

const trendBadge = computed(() => academicTrend.value ? trendLabelMap[academicTrend.value.trend] : null)

const trendChartOptions = computed(() => ({
  chart: { id: 'academic-trend', toolbar: { show: false } },
  xaxis: { categories: academicTrend.value?.points.map(p => p.label) || [] },
  colors: ['#7b2183'],
  grid: { borderColor: 'var(--app-border)', strokeDashArray: 4 },
  dataLabels: { enabled: true, formatter: (val: number) => `${val}%` },
  yaxis: { min: 0, max: 100 }
}))

const trendChartSeries = computed(() => [{
  name: 'Average Score',
  data: academicTrend.value?.points.map(p => p.score) || []
}])

async function loadTrend() {
  if (!filters.termId) return
  await reportStore.fetchAcademicTrend(apiFilters.value)
}

watch(apiFilters, loadTrend)

onMounted(async () => {
  useAppStore().setTitle('Academic Trends')
  document.title = 'Academic Trends | Skultem'
  await ensureLoaded()
  await loadTrend()
})

definePageMeta({
  role: [Role.ADMIN, Role.OWNER, Role.PROPRIETOR]
})
</script>
