<template>
  <div class="space-y-4 px-4 md:px-6">
    <UCard>
      <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4 print:hidden">
        <UFormField label="Report Type">
          <USelectMenu v-model="form.reportType" :items="reportTypes" value-key="value" label-key="label"
            class="w-full" />
        </UFormField>

        <UFormField v-if="form.reportType === 'TERM_SUMMARY' || (isGender && form.genderPeriod === 'TERM')" label="Term">
          <USelectMenu v-model="form.termId" :items="terms" value-key="value" label-key="label"
            placeholder="Select term" class="w-full" />
        </UFormField>

        <UFormField v-if="isGender" label="Period">
          <USelectMenu v-model="form.genderPeriod" :items="genderPeriods" value-key="value" label-key="label"
            class="w-full" />
        </UFormField>

        <UFormField v-if="isGender" label="Class">
          <USelectMenu v-model="form.genderClassId" :items="genderClasses" value-key="value" label-key="label"
            class="w-full" />
        </UFormField>

        <UFormField v-else label="Class">
          <USelectMenu v-model="form.classSessionId" :items="classSessions" :loading="loadingClasses"
            value-key="value" label-key="label" placeholder="Select class" class="w-full" />
        </UFormField>

        <UFormField v-if="isGender && form.genderPeriod === 'WEEK'" label="Week of">
          <UInput v-model="form.date" type="date" class="w-full" />
        </UFormField>
        <UFormField v-else-if="isGender && form.genderPeriod === 'MONTH'" label="Month">
          <UInput v-model="form.month" type="month" class="w-full" />
        </UFormField>
        <UFormField v-else-if="isGender && form.genderPeriod === 'YEAR'" label="Period">
          <UInput :model-value="academicYearLabel" disabled class="w-full" />
        </UFormField>
        <UFormField v-else-if="form.reportType === 'DAILY_REGISTER'" label="Date">
          <UInput v-model="form.date" type="date" class="w-full" />
        </UFormField>
        <UFormField v-else-if="form.reportType === 'MONTHLY_SUMMARY'" label="Month">
          <UInput v-model="form.month" type="month" class="w-full" />
        </UFormField>
      </div>

      <div class="mt-4 flex justify-end print:hidden">
        <UButton icon="i-lucide-file-check-2" color="primary" :loading="generating" :disabled="!canGenerate"
          @click="generate">
          Generate Report
        </UButton>
      </div>
    </UCard>

    <UCard v-if="generating">
      <div class="flex flex-col items-center justify-center py-14 text-center">
        <UIcon name="i-lucide-loader-circle" class="mb-3 size-8 animate-spin text-primary" />
        <p class="text-sm font-medium text-highlighted">Generating report...</p>
      </div>
    </UCard>

    <UCard v-else-if="!hasReport">
      <div class="flex flex-col items-center justify-center py-14 text-center">
        <UIcon name="i-lucide-file-check-2" class="mb-3 size-10 text-muted" />
        <p class="text-sm font-medium text-highlighted">No report generated yet</p>
        <p class="mt-1 max-w-sm text-xs text-muted">
          Choose a report type and the filters above, then press Generate Report.
        </p>
      </div>
    </UCard>

    <UCard v-else-if="isEmptyReport">
      <div class="flex flex-col items-center justify-center py-14 text-center">
        <UIcon name="i-lucide-calendar-x" class="mb-3 size-10 text-muted" />
        <p class="text-sm font-medium text-highlighted">No attendance records found for this period.</p>
      </div>
    </UCard>

    <template v-else>
      <Heading title="Report Ready" subtitle="Preview below, then print or download as PDF." class="print:hidden">
        <UButton icon="i-lucide-download" color="primary" class="justify-center" :loading="downloading"
          @click="downloadPdf">
          Download PDF
        </UButton>
      </Heading>

      <div id="inspection-report-preview" class="rounded-lg bg-white p-6 text-gray-900 sm:p-8">
        <!-- Header -->
        <div class="-m-6 mb-6 border-b-4 border-primary-500 pb-5 pt-6 text-center sm:-m-8 sm:mb-6 sm:pt-8">
          <img v-if="logoSrc" :src="logoSrc" class="mx-auto size-40 object-contain" alt="School logo">
          <h2 class="text-xl font-black tracking-wide">{{ schoolName }}</h2>
          <p class="mt-1 text-sm font-semibold text-gray-600">{{ meta!.title }}</p>
          <div class="mt-3 space-y-0.5 text-xs text-gray-500">
            <p>Academic Year: {{ meta!.academicYear }}<template v-if="meta!.term"> &middot; Term: {{ meta!.term }}</template></p>
            <p>Class: {{ meta!.className }} &middot; Report Period: {{ meta!.period }}</p>
            <p>Generated by: Skultem &middot; Generated Date: {{ meta!.generated }}</p>
          </div>
        </div>

        <!-- Body: Attendance by Gender (school-wide / per class, for the Ministry) -->
        <template v-if="isGender && genderSummary">
          <div class="mb-6 grid grid-cols-2 gap-3 sm:grid-cols-4">
            <div class="rounded-xl bg-primary-50 p-3 text-center">
              <p class="text-xs text-gray-500">Boys Present</p>
              <p class="text-xl font-bold text-primary-600">{{ genderSummary.totals.boysPresent }}</p>
            </div>
            <div class="rounded-xl bg-primary-50 p-3 text-center">
              <p class="text-xs text-gray-500">Girls Present</p>
              <p class="text-xl font-bold text-primary-600">{{ genderSummary.totals.girlsPresent }}</p>
            </div>
            <div class="rounded-xl bg-primary-50 p-3 text-center">
              <p class="text-xs text-gray-500">Boys Attendance</p>
              <p class="text-xl font-bold text-primary-600">{{ genderSummary.totals.boysAttendancePercentage }}%</p>
            </div>
            <div class="rounded-xl bg-primary-50 p-3 text-center">
              <p class="text-xs text-gray-500">Girls Attendance</p>
              <p class="text-xl font-bold text-primary-600">{{ genderSummary.totals.girlsAttendancePercentage }}%</p>
            </div>
          </div>

          <div class="overflow-x-auto">
            <table class="w-full min-w-max border-collapse text-sm">
              <thead>
                <tr class="bg-gray-50">
                  <th class="border border-gray-200 p-2.5 text-left font-semibold">Class</th>
                  <th class="border border-gray-200 p-2.5 text-center font-semibold">Boys Present</th>
                  <th class="border border-gray-200 p-2.5 text-center font-semibold">Girls Present</th>
                  <th class="border border-gray-200 p-2.5 text-center font-semibold">Total Present</th>
                  <th class="border border-gray-200 p-2.5 text-center font-semibold">Boys %</th>
                  <th class="border border-gray-200 p-2.5 text-center font-semibold">Girls %</th>
                  <th class="border border-gray-200 p-2.5 text-center font-semibold">Overall %</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="c in sortedGenderClasses" :key="c.classId">
                  <td class="border border-gray-200 p-2.5">{{ c.className }}</td>
                  <td class="border border-gray-200 p-2.5 text-center">{{ c.totals.boysPresent }}</td>
                  <td class="border border-gray-200 p-2.5 text-center">{{ c.totals.girlsPresent }}</td>
                  <td class="border border-gray-200 p-2.5 text-center">{{ c.totals.boysPresent + c.totals.girlsPresent }}</td>
                  <td class="border border-gray-200 p-2.5 text-center">{{ c.totals.boysAttendancePercentage }}%</td>
                  <td class="border border-gray-200 p-2.5 text-center">{{ c.totals.girlsAttendancePercentage }}%</td>
                  <td class="border border-gray-200 p-2.5 text-center font-semibold">{{ c.totals.overallAttendancePercentage }}%</td>
                </tr>
              </tbody>
              <tfoot v-if="genderSummary.classes.length > 1">
                <tr class="bg-gray-50 font-semibold">
                  <td class="border border-gray-200 p-2.5">Total</td>
                  <td class="border border-gray-200 p-2.5 text-center">{{ genderSummary.totals.boysPresent }}</td>
                  <td class="border border-gray-200 p-2.5 text-center">{{ genderSummary.totals.girlsPresent }}</td>
                  <td class="border border-gray-200 p-2.5 text-center">{{ genderSummary.totals.boysPresent + genderSummary.totals.girlsPresent }}</td>
                  <td class="border border-gray-200 p-2.5 text-center">{{ genderSummary.totals.boysAttendancePercentage }}%</td>
                  <td class="border border-gray-200 p-2.5 text-center">{{ genderSummary.totals.girlsAttendancePercentage }}%</td>
                  <td class="border border-gray-200 p-2.5 text-center">{{ genderSummary.totals.overallAttendancePercentage }}%</td>
                </tr>
              </tfoot>
            </table>
          </div>

          <p class="mt-3 text-xs text-gray-500">
            "Present" counts students marked present or late, per student per school day, from {{ genderSummary.startDate }}
            to {{ genderSummary.endDate }}. Percentages are over recorded school days (holidays and unmarked days excluded).
          </p>
        </template>

        <!-- Body: Daily Register -->
        <template v-else-if="report?.reportType === 'DAILY_REGISTER'">
          <div class="mb-6 grid grid-cols-2 gap-3 sm:grid-cols-4">
            <div class="rounded-xl bg-primary-50 p-3 text-center">
              <p class="text-xs text-gray-500">Present</p>
              <p class="text-xl font-bold text-primary-600">{{ dailyPayload!.presentCount }}</p>
            </div>
            <div class="rounded-xl bg-primary-50 p-3 text-center">
              <p class="text-xs text-gray-500">Absent</p>
              <p class="text-xl font-bold text-primary-600">{{ dailyPayload!.absentCount + dailyPayload!.excusedCount }}</p>
            </div>
            <div class="rounded-xl bg-primary-50 p-3 text-center">
              <p class="text-xs text-gray-500">Late</p>
              <p class="text-xl font-bold text-primary-600">{{ dailyPayload!.lateCount }}</p>
            </div>
            <div class="rounded-xl bg-primary-50 p-3 text-center">
              <p class="text-xs text-gray-500">Total Students</p>
              <p class="text-xl font-bold text-primary-600">{{ dailyPayload!.totalStudents }}</p>
            </div>
          </div>

          <div class="mb-6 grid grid-cols-2 gap-3">
            <div class="rounded-xl bg-primary-50 p-3 text-center">
              <p class="text-xs text-gray-500">Boys Present</p>
              <p class="text-lg font-bold text-primary-600">{{ dailyPayload!.presentBoys }} / {{ dailyPayload!.totalBoys }}</p>
            </div>
            <div class="rounded-xl bg-primary-50 p-3 text-center">
              <p class="text-xs text-gray-500">Girls Present</p>
              <p class="text-lg font-bold text-primary-600">{{ dailyPayload!.presentGirls }} / {{ dailyPayload!.totalGirls }}</p>
            </div>
          </div>

          <div class="overflow-x-auto">
            <table class="w-full min-w-max border-collapse text-sm">
              <thead>
                <tr class="bg-gray-50">
                  <th class="border border-gray-200 p-2.5 text-left font-semibold">Student</th>
                  <th class="border border-gray-200 p-2.5 text-left font-semibold">Status</th>
                  <th class="border border-gray-200 p-2.5 text-left font-semibold">Recorded By</th>
                  <th class="border border-gray-200 p-2.5 text-left font-semibold">Time</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="r in dailyPayload!.records" :key="r.enrollmentId">
                  <td class="border border-gray-200 p-2.5">{{ r.studentName }}</td>
                  <td class="border border-gray-200 p-2.5">{{ dailyStatusLabel(r) }}</td>
                  <td class="border border-gray-200 p-2.5">{{ r.recordedBy || '—' }}</td>
                  <td class="border border-gray-200 p-2.5">{{ clockTime(r.recordedAt) }}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </template>

        <!-- Body: Monthly Summary -->
        <template v-else-if="report?.reportType === 'MONTHLY_SUMMARY'">
          <div class="mb-6 grid grid-cols-2 gap-3">
            <div class="rounded-xl bg-primary-50 p-3 text-center">
              <p class="text-xs text-gray-500">Boys Attendance</p>
              <p class="text-lg font-bold text-primary-600">{{ monthlyGenderTotals.presentBoys }} / {{ monthlyGenderTotals.totalBoys }}</p>
            </div>
            <div class="rounded-xl bg-primary-50 p-3 text-center">
              <p class="text-xs text-gray-500">Girls Attendance</p>
              <p class="text-lg font-bold text-primary-600">{{ monthlyGenderTotals.presentGirls }} / {{ monthlyGenderTotals.totalGirls }}</p>
            </div>
          </div>

          <div class="overflow-x-auto">
            <table class="w-full min-w-max border-collapse text-sm">
              <thead>
                <tr class="bg-gray-50">
                  <th class="border border-gray-200 p-2.5 text-left font-semibold">Student</th>
                  <th class="border border-gray-200 p-2.5 text-center font-semibold">School Days</th>
                  <th class="border border-gray-200 p-2.5 text-center font-semibold">Present</th>
                  <th class="border border-gray-200 p-2.5 text-center font-semibold">Absent</th>
                  <th class="border border-gray-200 p-2.5 text-center font-semibold">Late</th>
                  <th class="border border-gray-200 p-2.5 text-center font-semibold">Attendance %</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="s in sortedMonthly" :key="s.studentId" :class="s.belowThreshold ? 'bg-red-50' : ''">
                  <td class="border border-gray-200 p-2.5">{{ s.studentName }}</td>
                  <td class="border border-gray-200 p-2.5 text-center">{{ s.schoolDays }}</td>
                  <td class="border border-gray-200 p-2.5 text-center">{{ s.present }}</td>
                  <td class="border border-gray-200 p-2.5 text-center">{{ s.absent }}</td>
                  <td class="border border-gray-200 p-2.5 text-center">{{ s.late }}</td>
                  <td class="border border-gray-200 p-2.5 text-center font-semibold"
                    :class="s.belowThreshold ? 'text-red-600' : 'text-gray-700'">
                    {{ s.attendancePercentage != null ? `${s.attendancePercentage}%` : '—' }}
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </template>

        <!-- Body: Term Summary -->
        <template v-else>
          <div class="mb-6 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">
            <div class="rounded-xl bg-primary-50 p-3 text-center">
              <p class="text-xs text-gray-500">Total Students</p>
              <p class="text-lg font-bold text-primary-600">{{ termPayload!.totalStudents }}</p>
            </div>
            <div class="rounded-xl bg-primary-50 p-3 text-center">
              <p class="text-xs text-gray-500">Avg. Attendance</p>
              <p class="text-lg font-bold text-primary-600">{{ termPayload!.averageAttendance }}%</p>
            </div>
            <div class="rounded-xl bg-primary-50 p-3 text-center">
              <p class="text-xs text-gray-500">Below {{ thresholdText([termPayload?.threshold], threshold) }}</p>
              <p class="text-lg font-bold text-primary-600">{{ termPayload!.studentsBelowThreshold }}</p>
            </div>
            <div class="rounded-xl bg-primary-50 p-3 text-center">
              <p class="text-xs text-gray-500">Total Present</p>
              <p class="text-lg font-bold text-primary-600">{{ termPayload!.totalPresent }}</p>
            </div>
            <div class="rounded-xl bg-primary-50 p-3 text-center">
              <p class="text-xs text-gray-500">Total Absent</p>
              <p class="text-lg font-bold text-primary-600">{{ termPayload!.totalAbsent }}</p>
            </div>
            <div class="rounded-xl bg-primary-50 p-3 text-center">
              <p class="text-xs text-gray-500">Total Late</p>
              <p class="text-lg font-bold text-primary-600">{{ termPayload!.totalLate }}</p>
            </div>
          </div>

          <div class="mb-6 grid grid-cols-2 gap-3">
            <div class="rounded-xl bg-primary-50 p-3 text-center">
              <p class="text-xs text-gray-500">Boys Attendance</p>
              <p class="text-lg font-bold text-primary-600">{{ termPayload!.presentBoys }} / {{ termPayload!.totalBoys }}</p>
            </div>
            <div class="rounded-xl bg-primary-50 p-3 text-center">
              <p class="text-xs text-gray-500">Girls Attendance</p>
              <p class="text-lg font-bold text-primary-600">{{ termPayload!.presentGirls }} / {{ termPayload!.totalGirls }}</p>
            </div>
          </div>

          <div class="overflow-x-auto">
            <table class="w-full min-w-max border-collapse text-sm">
              <thead>
                <tr class="bg-gray-50">
                  <th class="border border-gray-200 p-2.5 text-left font-semibold">Student</th>
                  <th class="border border-gray-200 p-2.5 text-center font-semibold">School Days</th>
                  <th class="border border-gray-200 p-2.5 text-center font-semibold">Present</th>
                  <th class="border border-gray-200 p-2.5 text-center font-semibold">Absent</th>
                  <th class="border border-gray-200 p-2.5 text-center font-semibold">Late</th>
                  <th class="border border-gray-200 p-2.5 text-center font-semibold">Attendance %</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="s in sortedTermStudents" :key="s.studentId" :class="s.belowThreshold ? 'bg-red-50' : ''">
                  <td class="border border-gray-200 p-2.5">{{ s.studentName }}</td>
                  <td class="border border-gray-200 p-2.5 text-center">{{ s.schoolDays }}</td>
                  <td class="border border-gray-200 p-2.5 text-center">{{ s.present }}</td>
                  <td class="border border-gray-200 p-2.5 text-center">{{ s.absent }}</td>
                  <td class="border border-gray-200 p-2.5 text-center">{{ s.late }}</td>
                  <td class="border border-gray-200 p-2.5 text-center font-semibold"
                    :class="s.belowThreshold ? 'text-red-600' : 'text-gray-700'">
                    {{ s.attendancePercentage != null ? `${s.attendancePercentage}%` : '—' }}
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </template>

        <!-- Footer: Skultem-generated, not an official Ministry document - deliberately no MBSSE
             fields, seal or signature line beyond a plain school stamp placeholder. -->
        <div class="mt-10 grid grid-cols-1 gap-8 text-sm sm:grid-cols-2">
          <div class="space-y-6">
            <div>
              <p class="border-b border-gray-400 pb-1">&nbsp;</p>
              <p class="mt-1 text-xs text-gray-500">Prepared by (Signature)</p>
            </div>
            <div>
              <p class="border-b border-gray-400 pb-1">&nbsp;</p>
              <p class="mt-1 text-xs text-gray-500">Name</p>
            </div>
            <div>
              <p class="border-b border-gray-400 pb-1">&nbsp;</p>
              <p class="mt-1 text-xs text-gray-500">Position</p>
            </div>
            <div>
              <p class="border-b border-gray-400 pb-1">&nbsp;</p>
              <p class="mt-1 text-xs text-gray-500">Date</p>
            </div>
          </div>
          <div class="flex items-end justify-center sm:justify-end">
            <div class="flex h-28 w-28 items-center justify-center rounded-full border-2 border-dashed border-gray-300 text-center text-[10px] text-gray-400">
              School Stamp
            </div>
          </div>
        </div>

        <p class="mt-8 text-center text-[10px] uppercase tracking-widest text-gray-300">
          Generated by Skultem &middot; Not an official MBSSE document
        </p>
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
const academicYearStore = useAcademicYearStore()
const termStore = useTermStore()
const classSessionStore = useClassSessionStore()
const attendanceStore = useAttendanceStore()
const { school } = useSchoolInfo()
const { threshold } = useAttendanceThreshold()
const { success, error: toastError } = useNotify()

type ReportKind = InspectionReportType | 'GENDER_SUMMARY'

const reportStore = useAcademicReportStore()
const classStore = useClassStore()

const reportTypes: { label: string, value: ReportKind }[] = [
  { label: 'Daily Attendance Register', value: 'DAILY_REGISTER' },
  { label: 'Monthly Attendance Summary', value: 'MONTHLY_SUMMARY' },
  { label: 'Term Attendance Summary', value: 'TERM_SUMMARY' },
  { label: 'Attendance by Gender (Ministry Return)', value: 'GENDER_SUMMARY' }
]

const genderPeriods = [
  { label: 'Week', value: 'WEEK' },
  { label: 'Month', value: 'MONTH' },
  { label: 'Term', value: 'TERM' },
  { label: 'Year', value: 'YEAR' }
]

const form = reactive({
  reportType: 'DAILY_REGISTER' as ReportKind,
  genderPeriod: 'TERM' as 'WEEK' | 'MONTH' | 'TERM' | 'YEAR',
  genderClassId: '__all',
  academicYearId: '',
  termId: '',
  classSessionId: '',
  date: new Date().toISOString().split('T')[0] as string,
  month: new Date().toISOString().slice(0, 7)
})

const loadingClasses = ref(false)
const localClassSessions = ref<ClassSession[]>([])
const generating = ref(false)
const downloading = ref(false)
const { logoSrc, loadLogo, ready: logoReady } = useReportLogo()

const academicYears = computed(() => academicYearStore.list)
const terms = computed(() => termStore.records.map(t => ({ label: t.name, value: t.id })))
const classSessions = computed(() => localClassSessions.value.map(e => {
  let label = `${e.clazz} (${e.sectionName})`
  if (e.streamName !== 'N/A') label += ` - ${e.streamName}`
  return { label, value: e.id }
}))

const isGender = computed(() => form.reportType === 'GENDER_SUMMARY')
const genderSummary = computed(() => isGender.value ? reportStore.genderAttendanceSummary : null)
const genderClasses = computed(() => [
  { label: 'All classes', value: '__all' },
  ...classStore.records.map(c => ({ label: c.name, value: c.id }))
])

const report = computed(() => isGender.value ? null : attendanceStore.inspectionReport)
// Header details are captured when a report is generated, so editing a filter afterwards can't relabel
// the report on screen; the report is only shown while its type matches the selected Report Type.
const meta = ref<{ kind: ReportKind, title: string, academicYear: string, term: string | null, className: string, period: string, generated: string } | null>(null)
const hasReport = computed(() => !!meta.value && meta.value.kind === form.reportType
  && (isGender.value ? !!genderSummary.value : !!report.value))
const dailyPayload = computed(() => report.value?.reportType === 'DAILY_REGISTER' ? report.value.payload as DailyAttendanceRegister : null)
const monthlyPayload = computed(() => report.value?.reportType === 'MONTHLY_SUMMARY' ? report.value.payload as StudentAttendanceSummary[] : [])
const termPayload = computed(() => report.value?.reportType === 'TERM_SUMMARY' ? report.value.payload as TermAttendanceSummary : null)

// Monthly Summary's payload is a plain per-student array (no stats wrapper on the backend), so
// the gender split is computed here the same way monthly-summary.vue does it - bounded to one
// class's roster, cheap either way.
const monthlyGenderTotals = computed(() => {
  const boys = monthlyPayload.value.filter(s => s.gender === 'MALE')
  const girls = monthlyPayload.value.filter(s => s.gender === 'FEMALE')
  return {
    totalBoys: boys.length,
    totalGirls: girls.length,
    presentBoys: boys.reduce((sum, s) => sum + s.present + s.late, 0),
    presentGirls: girls.reduce((sum, s) => sum + s.present + s.late, 0)
  }
})

// Ranking-style tables list the highest attendance first.
const sortedGenderClasses = computed(() => sortByDesc(genderSummary.value?.classes, c => c.totals.overallAttendancePercentage))
const sortedMonthly = computed(() => sortByDesc(monthlyPayload.value, s => s.attendancePercentage))
const sortedTermStudents = computed(() => sortByDesc(termPayload.value?.students, s => s.attendancePercentage))

const isEmptyReport = computed(() => {
  if (isGender.value) return !!genderSummary.value && genderSummary.value.classes.length === 0
  if (!report.value) return false
  if (dailyPayload.value) return dailyPayload.value.totalStudents === 0
  if (report.value.reportType === 'MONTHLY_SUMMARY') return monthlyPayload.value.length === 0
  if (termPayload.value) return termPayload.value.students.length === 0
  return false
})

const canGenerate = computed(() => {
  if (isGender.value) {
    if (form.genderPeriod === 'WEEK') return !!form.date
    if (form.genderPeriod === 'MONTH') return !!form.month
    if (form.genderPeriod === 'TERM') return !!form.termId
    return true
  }
  if (!form.classSessionId) return false
  if (form.reportType === 'DAILY_REGISTER') return !!form.date
  if (form.reportType === 'MONTHLY_SUMMARY') return !!form.month
  return !!form.termId
})

const academicYearLabel = computed(() =>
  academicYears.value.find(y => y.value === form.academicYearId)?.label || academicYearStore.activeYear?.name || '—')
const termLabel = computed(() => terms.value.find(t => t.value === form.termId)?.label || '—')
const classLabel = computed(() => isGender.value
  ? (genderClasses.value.find(c => c.value === form.genderClassId)?.label || '—')
  : classSessions.value.find(c => c.value === form.classSessionId)?.label || '—')
const periodLabel = computed(() => {
  if (isGender.value) {
    const s = genderSummary.value
    const range = s ? `${s.startDate} – ${s.endDate}` : '—'
    return form.genderPeriod === 'TERM' ? `${termLabel.value} (${range})` : range
  }
  if (form.reportType === 'DAILY_REGISTER') {
    return form.date ? new Date(form.date).toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' }) : '—'
  }
  if (form.reportType === 'MONTHLY_SUMMARY') {
    const [year, month] = form.month.split('-').map(Number)
    return year && month ? new Date(year, month - 1, 1).toLocaleDateString(undefined, { year: 'numeric', month: 'long' }) : '—'
  }
  return termLabel.value
})
const generatedDate = computed(() => new Date().toLocaleDateString())
const schoolName = computed(() => school.value?.name || 'Skultem')

function dailyStatusLabel(r: DailyAttendanceRegisterRecord) {
  if (!r.marked) return 'Not Marked'
  if (r.present && r.late) return 'Late'
  if (r.present) return 'Present'
  if (r.excused) return 'Excused'
  return 'Absent'
}

function clockTime(value: string | null) {
  return value ? formatTime(value) : '—'
}

function sanitizeFilename(value: string) {
  return String(value).replace(/[^a-z0-9-_]/gi, '-')
}

async function loadClasses() {
  loadingClasses.value = true
  try {
    await classSessionStore.fetchAll(1, 200, form.academicYearId || undefined)
    localClassSessions.value = classSessionStore.records
    if (!form.classSessionId) form.classSessionId = localClassSessions.value[0]?.id || ''
  } finally {
    loadingClasses.value = false
  }
}

function snapshotMeta() {
  const usesTerm = form.reportType === 'TERM_SUMMARY' || (isGender.value && form.genderPeriod === 'TERM')
  meta.value = {
    kind: form.reportType,
    title: isGender.value ? 'Attendance Report by Gender' : 'Student Attendance Report',
    academicYear: academicYearLabel.value,
    term: usesTerm ? termLabel.value : null,
    className: classLabel.value,
    period: periodLabel.value,
    generated: generatedDate.value
  }
}

async function generate() {
  if (!canGenerate.value) return
  generating.value = true
  try {
    if (isGender.value) {
      await reportStore.fetchGenderAttendanceSummary({
        period: form.genderPeriod,
        academicYearId: form.academicYearId || undefined,
        termId: form.genderPeriod === 'TERM' ? form.termId : undefined,
        classId: form.genderClassId === '__all' ? undefined : form.genderClassId,
        date: form.genderPeriod === 'MONTH' ? `${form.month}-01` : form.date
      })
      snapshotMeta()
      return
    }

    const [year, month] = form.month.split('-').map(Number)
    await attendanceStore.fetchInspectionReport({
      reportType: form.reportType,
      classSessionId: form.classSessionId,
      termId: form.reportType === 'TERM_SUMMARY' ? form.termId : undefined,
      date: form.reportType === 'DAILY_REGISTER' ? form.date : undefined,
      year: form.reportType === 'MONTHLY_SUMMARY' ? year : undefined,
      month: form.reportType === 'MONTHLY_SUMMARY' ? month : undefined
    })
    snapshotMeta()
  } catch (err: any) {
    toastError(err?.message || 'Failed to generate report')
  } finally {
    generating.value = false
  }
}

function printReport() {
  window.print()
}

async function downloadPdf() {
  if (!hasReport.value) return
  downloading.value = true
  try {
    await logoReady() // the print-safe logo must be in before the PDF is drawn
    const { $generatePdf } = useNuxtApp()
    await $generatePdf('#inspection-report-preview', `inspection-report-${sanitizeFilename(form.reportType)}`)
    success('Report downloaded')
  } catch (err: any) {
    toastError(err?.message || 'Failed to generate PDF')
  } finally {
    downloading.value = false
  }
}

watch(() => form.academicYearId, loadClasses)

watch(() => form.classSessionId, id => loadLogo(localClassSessions.value.find(c => c.id === id)?.classLevel ?? null)) // that class's section logo

// No year dropdown on this page: reports follow the header's year switcher (viewing year).
watch(() => academicYearStore.viewingYearId || academicYearStore.activeYear?.id || '', (id) => { form.academicYearId = id })

onMounted(async () => {
  loadLogo() // not awaited - fetches in the background, doesn't block the report's own data

  useAppStore().setTitle('Inspection Reports')
  document.title = 'Inspection Reports | Skultem'

  await academicYearStore.fetchAll(1, 100)
  form.academicYearId = academicYearStore.viewingYearId || academicYearStore.activeYear?.id || ''

  await termStore.fetchAll(1, 100)
  const active = await termStore.getActive()
  form.termId = active?.id || termStore.records[0]?.id || ''

  await Promise.all([loadClasses(), classStore.fetchAll(1, 200)])
})

definePageMeta({
  role: [Role.ADMIN, Role.OWNER, Role.PROPRIETOR, Role.PRINCIPAL, Role.SUPER_ADMIN]
})
</script>
