<template>
  <div class="space-y-4 px-4 md:px-6">
    <Heading title="Daily Register" subtitle="View, print or export the staff attendance register for a specific date.">
      <UButton icon="i-lucide-download" color="primary" class="justify-center" :loading="downloading"
        :disabled="!roster" @click="downloadPdf">
        Export PDF
      </UButton>
    </Heading>

    <HrSectionNav />

    <UCard>
      <div class="grid gap-4 sm:grid-cols-2">
        <UFormField label="Date">
          <UInput v-model="filters.date" type="date" class="w-full" />
        </UFormField>

        <UFormField label="Teacher (optional)">
          <UInput v-model="search" icon="i-lucide-search" placeholder="Search teacher..." class="w-full" />
        </UFormField>
      </div>
    </UCard>

    <UCard v-if="loading">
      <div class="space-y-3">
        <USkeleton class="h-8 w-64" />
        <USkeleton v-for="i in 6" :key="i" class="h-8 w-full" />
      </div>
    </UCard>

    <UCard v-else-if="!roster || !filteredEntries.length">
      <div class="flex flex-col items-center justify-center py-14 text-center">
        <UIcon name="i-lucide-calendar-x" class="mb-3 size-10 text-muted" />
        <p class="text-sm font-medium text-highlighted">No attendance records found for this period.</p>
      </div>
    </UCard>

    <template v-else>
      <div id="teacher-daily-register-preview" class="rounded-lg bg-white text-gray-900 px-2"
        style="background-color: #ffffff; color: #111827;">
        <div class="mb-4 border-b-4 border-primary-500 px-2 pb-5 pt-6 text-center sm:pt-8">
          <img v-if="logoSrc" :src="logoSrc" class="mx-auto size-40 object-contain" alt="School logo">
          <h2 class="text-xl font-black tracking-wide dark:text-gray-900">{{ schoolName }}</h2>
          <p class="mt-1 text-sm font-semibold text-gray-600 dark:text-gray-600">Staff Daily Attendance Register</p>
          <div class="mt-3 flex flex-wrap items-center justify-center gap-x-3 gap-y-1 text-xs text-gray-500 dark:text-gray-500">
            <span>Academic Year: {{ academicYearLabel }}</span>
            <span>Term: {{ termLabel }}</span>
            <span>Date: {{ formattedDate }}</span>
          </div>
        </div>

        <div class="mb-6 grid grid-cols-2 gap-3 sm:grid-cols-5">
          <div class="rounded-xl bg-primary-50 p-3 text-center">
            <p class="text-xs text-gray-500 dark:text-gray-500">Present</p>
            <p class="text-xl font-bold text-primary-600">{{ roster.presentCount }}</p>
          </div>
          <div class="rounded-xl bg-primary-50 p-3 text-center">
            <p class="text-xs text-gray-500 dark:text-gray-500">Absent</p>
            <p class="text-xl font-bold text-primary-600">{{ roster.absentCount }}</p>
          </div>
          <div class="rounded-xl bg-primary-50 p-3 text-center">
            <p class="text-xs text-gray-500 dark:text-gray-500">Late</p>
            <p class="text-xl font-bold text-primary-600">{{ roster.lateCount }}</p>
          </div>
          <div class="rounded-xl bg-primary-50 p-3 text-center">
            <p class="text-xs text-gray-500 dark:text-gray-500">Excused</p>
            <p class="text-xl font-bold text-primary-600">{{ roster.excusedCount }}</p>
          </div>
          <div class="rounded-xl bg-primary-50 p-3 text-center">
            <p class="text-xs text-gray-500 dark:text-gray-500">Total Teachers</p>
            <p class="text-xl font-bold text-primary-600">{{ roster.totalCount }}</p>
          </div>
        </div>

        <div class="overflow-x-auto">
          <table class="w-full min-w-max border-collapse text-sm">
            <thead>
              <tr class="bg-gray-50">
                <th class="border border-gray-200 p-2.5 text-left font-semibold">Teacher</th>
                <th class="border border-gray-200 p-2.5 text-left font-semibold">Status</th>
                <th class="border border-gray-200 p-2.5 text-left font-semibold">Recorded By</th>
                <th class="border border-gray-200 p-2.5 text-left font-semibold">Time</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="row in filteredEntries" :key="row.teacher.id">
                <td class="border border-gray-200 p-2.5">{{ teacherName(row.teacher) }}</td>
                <td class="border border-gray-200 p-2.5 font-semibold" :style="{ color: statusColor(row.status) }">
                  {{ statusLabel(row.status) }}
                </td>
                <td class="border border-gray-200 p-2.5">{{ recordedByLabel(row) }}</td>
                <td class="border border-gray-200 p-2.5">{{ rowClockInTime(row) }}</td>
              </tr>
            </tbody>
          </table>
        </div>

        <p class="mt-6 text-center text-[10px] uppercase tracking-widest text-gray-300">
          Generated by Skultem &middot; {{ generatedDate }}
        </p>
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
const academicYearStore = useAcademicYearStore()
const termStore = useTermStore()
const teacherAttendanceStore = useTeacherAttendanceStore()
const { school } = useSchoolInfo()

const filters = reactive({
  date: todayISO()
})

const search = ref('')
const downloading = ref(false)
const { success, error: toastError } = useNotify()

const activeTermName = ref('—')

const roster = computed(() => teacherAttendanceStore.roster)
const loading = computed(() => teacherAttendanceStore.loadingRoster)

const filteredEntries = computed(() => {
  const entries = roster.value?.entries || []
  if (!search.value.trim()) return entries

  const query = search.value.trim().toLowerCase()
  return entries.filter(row => teacherName(row.teacher).toLowerCase().includes(query))
})

const academicYearLabel = computed(() => academicYearStore.activeYear?.name || '—')
const termLabel = computed(() => activeTermName.value)
const formattedDate = computed(() => filters.date
  ? new Date(filters.date).toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' })
  : '—')
const generatedDate = computed(() => new Date().toLocaleDateString())
const schoolName = computed(() => school.value?.name || 'Skultem')
// The data: URI logo (safe for the PDF capture) of the viewer's own section, if they're limited to
// one; the school's plain logo shows meanwhile.
const { logoSrc: reportLogo, loadLogo } = useReportLogo()
const logoSrc = computed(() => reportLogo.value || school.value?.logo || '')

function todayISO() {
  return new Date().toISOString().split('T')[0] as string
}

function teacherName(teacher: Teacher) {
  return `${teacher.user?.givenNames || ''} ${teacher.user?.familyName || ''}`.trim()
}

function statusLabel(status: TeacherAttendanceStatus | null) {
  if (!status) return 'Not Marked'
  return TEACHER_ATTENDANCE_STATUS_OPTIONS.find(o => o.value === status)?.label || status
}

function statusColor(status: TeacherAttendanceStatus | null) {
  return {
    PRESENT: '#15803d',
    LATE: '#b45309',
    ABSENT: '#b91c1c',
    EXCUSED: '#1d4ed8'
  }[status || ''] || '#4b5563'
}

function recordedByLabel(row: TeacherRosterEntry) {
  if (row.recordedBy) return row.recordedBy
  if (row.clockedInAt) return row.clockInByAdmin ? 'Admin (clock-in)' : 'Self clock-in'
  return '—'
}

function rowClockInTime(row: TeacherRosterEntry) {
  return row.clockedInAt ? formatTime(row.clockedInAt) : '—'
}

function sanitizeFilename(value: string) {
  return String(value).replace(/[^a-z0-9-_]/gi, '-')
}

async function downloadPdf() {
  if (!roster.value) return
  downloading.value = true
  try {
    const { $generatePdf } = useNuxtApp()
    await $generatePdf('#teacher-daily-register-preview', `teacher-daily-register-${sanitizeFilename(filters.date)}`)
    success('Register downloaded')
  } catch (err: any) {
    toastError(err?.message || 'Failed to generate PDF')
  } finally {
    downloading.value = false
  }
}

watch(() => filters.date, () => teacherAttendanceStore.fetchRoster(filters.date))

onMounted(async () => {
  loadLogo() // not awaited - fetches in the background
  useAppStore().setTitle('Human Resource')
  useAppStore().setBack('/hr')
  document.title = 'Daily Register | HR | Skultem'

  await academicYearStore.fetchAll(1, 100)

  const active = await termStore.getActive()
  activeTermName.value = active?.name || '—'

  await teacherAttendanceStore.fetchRoster(filters.date)
})

definePageMeta({
  role: [Role.ADMIN, Role.OWNER, Role.PROPRIETOR]
})
</script>
