<template>
  <div class="space-y-4 px-4 md:px-6">
    <Heading title="Management Reports"
      subtitle="Generate a staff attendance document for internal school management use.">
      <UButton icon="i-lucide-file-text" color="primary" :loading="generating" :disabled="!canGenerate"
        @click="generate">
        Generate Report
      </UButton>
    </Heading>

    <HrSectionNav />

    <UCard>
      <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4 print:hidden">
        <UFormField label="Report Type">
          <USelectMenu v-model="form.reportType" :items="reportTypes" value-key="value" label-key="label"
            class="w-full" />
        </UFormField>

        <UFormField label="Term">
          <USelectMenu v-model="form.termId" :items="terms" value-key="value" label-key="label"
            placeholder="Select term" class="w-full" />
        </UFormField>

        <UFormField v-if="form.reportType === 'DAILY_REGISTER'" label="Date">
          <UInput v-model="form.date" type="date" class="w-full" />
        </UFormField>
        <UFormField v-else-if="form.reportType === 'MONTHLY_SUMMARY'" label="Month">
          <UInput v-model="form.month" type="month" class="w-full" />
        </UFormField>
        <UFormField v-else label="Period">
          <UInput :model-value="termLabel" disabled class="w-full" />
        </UFormField>
      </div>
    </UCard>

    <UCard v-if="generating">
      <div class="flex flex-col items-center justify-center py-14 text-center">
        <UIcon name="i-lucide-loader-circle" class="mb-3 size-8 animate-spin text-primary" />
        <p class="text-sm font-medium text-highlighted">Generating report...</p>
      </div>
    </UCard>

    <UCard v-else-if="!report">
      <div class="flex flex-col items-center justify-center py-14 text-center">
        <UIcon name="i-lucide-file-text" class="mb-3 size-10 text-muted" />
        <p class="text-sm font-medium text-highlighted">No report generated yet</p>
        <p class="mt-1 max-w-sm text-xs text-muted">
          Choose a report type and the filters above, then press Generate Report.
        </p>
      </div>
    </UCard>

    <UCard v-else-if="isEmptyReport">
      <div class="flex flex-col items-center justify-center py-14 text-center">
        <UIcon name="i-lucide-calendar-x" class="mb-3 size-10 text-muted" />
        <p class="text-sm font-medium text-highlighted">No attendance records found for this period.</p>
      </div>
    </UCard>

    <template v-else>
      <Heading title="Report Ready" subtitle="Preview below, then print or download as PDF." class="print:hidden">
        <UButton icon="i-lucide-printer" variant="outline" color="neutral" class="justify-center" @click="printReport">
          Print
        </UButton>
        <UButton icon="i-lucide-download" color="primary" class="justify-center" :loading="downloading"
          @click="downloadPdf">
          Download PDF
        </UButton>
      </Heading>

      <div id="teacher-management-report-preview" class="rounded-lg bg-white text-gray-900 px-2">
        <div class="mb-4 border-b-4 border-primary-500 px-6 pb-5 pt-6 text-center sm:px-8 sm:pt-8">
          <img v-if="logoSrc" :src="logoSrc" class="mx-auto size-40 object-contain" alt="School logo">
          <h2 class="text-xl font-black tracking-wide">{{ schoolName }}</h2>
          <p class="mt-1 text-sm font-semibold text-gray-600">Staff Attendance Report</p>
          <div class="mt-3 space-y-0.5 text-xs text-gray-500">
            <p>Term: {{ termLabel }} &middot; Report Period: {{ periodLabel }}</p>
            <p>Generated by: Skultem &middot; Generated Date: {{ generatedDate }}</p>
          </div>
        </div>

        <!-- Body: Daily Register -->
        <template v-if="report!.reportType === 'DAILY_REGISTER'">
          <div class="mb-6 grid grid-cols-2 gap-3 sm:grid-cols-5">
            <div class="rounded-xl bg-primary-50 p-3 text-center">
              <p class="text-xs text-gray-500">Present</p>
              <p class="text-xl font-bold text-primary-600">{{ dailyPayload!.presentCount }}</p>
            </div>
            <div class="rounded-xl bg-primary-50 p-3 text-center">
              <p class="text-xs text-gray-500">Absent</p>
              <p class="text-xl font-bold text-primary-600">{{ dailyPayload!.absentCount }}</p>
            </div>
            <div class="rounded-xl bg-primary-50 p-3 text-center">
              <p class="text-xs text-gray-500">Late</p>
              <p class="text-xl font-bold text-primary-600">{{ dailyPayload!.lateCount }}</p>
            </div>
            <div class="rounded-xl bg-primary-50 p-3 text-center">
              <p class="text-xs text-gray-500">Excused</p>
              <p class="text-xl font-bold text-primary-600">{{ dailyPayload!.excusedCount }}</p>
            </div>
            <div class="rounded-xl bg-primary-50 p-3 text-center">
              <p class="text-xs text-gray-500">Total Teachers</p>
              <p class="text-xl font-bold text-primary-600">{{ dailyPayload!.totalCount }}</p>
            </div>
          </div>

          <div class="overflow-x-auto">
            <table class="w-full min-w-max border-collapse text-sm">
              <thead>
                <tr class="bg-gray-50">
                  <th class="border border-gray-200 p-2.5 text-left font-semibold">Teacher</th>
                  <th class="border border-gray-200 p-2.5 text-left font-semibold">Status</th>
                  <th class="border border-gray-200 p-2.5 text-left font-semibold">Recorded By</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="r in dailyPayload!.entries" :key="r.teacher.id">
                  <td class="border border-gray-200 p-2.5">{{ teacherName(r.teacher) }}</td>
                  <td class="border border-gray-200 p-2.5">{{ r.status || 'Not Marked' }}</td>
                  <td class="border border-gray-200 p-2.5">{{ r.recordedBy || '—' }}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </template>

        <!-- Body: Monthly Summary -->
        <template v-else-if="report!.reportType === 'MONTHLY_SUMMARY'">
          <div class="overflow-x-auto">
            <table class="w-full min-w-max border-collapse text-sm">
              <thead>
                <tr class="bg-gray-50">
                  <th class="border border-gray-200 p-2.5 text-left font-semibold">Teacher</th>
                  <th class="border border-gray-200 p-2.5 text-center font-semibold">Working Days</th>
                  <th class="border border-gray-200 p-2.5 text-center font-semibold">Present</th>
                  <th class="border border-gray-200 p-2.5 text-center font-semibold">Absent</th>
                  <th class="border border-gray-200 p-2.5 text-center font-semibold">Late</th>
                  <th class="border border-gray-200 p-2.5 text-center font-semibold">Attendance %</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="t in monthlyPayload" :key="t.teacherId">
                  <td class="border border-gray-200 p-2.5">{{ t.teacherName }}</td>
                  <td class="border border-gray-200 p-2.5 text-center">{{ t.workingDays }}</td>
                  <td class="border border-gray-200 p-2.5 text-center">{{ t.present }}</td>
                  <td class="border border-gray-200 p-2.5 text-center">{{ t.absent }}</td>
                  <td class="border border-gray-200 p-2.5 text-center">{{ t.late }}</td>
                  <td class="border border-gray-200 p-2.5 text-center font-semibold text-gray-700">
                    {{ t.attendancePercentage != null ? `${t.attendancePercentage}%` : '—' }}
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </template>

        <!-- Body: Term Summary -->
        <template v-else>
          <div class="mb-6 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">
            <div class="rounded-xl bg-primary-50 p-3 text-center">
              <p class="text-xs text-gray-500">Total Teachers</p>
              <p class="text-lg font-bold text-primary-600">{{ termPayload!.totalTeachers }}</p>
            </div>
            <div class="rounded-xl bg-primary-50 p-3 text-center">
              <p class="text-xs text-gray-500">Avg. Attendance</p>
              <p class="text-lg font-bold text-primary-600">{{ termPayload!.averageAttendance }}%</p>
            </div>
            <div class="rounded-xl bg-primary-50 p-3 text-center">
              <p class="text-xs text-gray-500">Total Present</p>
              <p class="text-lg font-bold text-primary-600">{{ termPayload!.totalPresent }}</p>
            </div>
            <div class="rounded-xl bg-primary-50 p-3 text-center">
              <p class="text-xs text-gray-500">Total Absent</p>
              <p class="text-lg font-bold text-primary-600">{{ termPayload!.totalAbsent }}</p>
            </div>
            <div class="rounded-xl bg-primary-50 p-3 text-center">
              <p class="text-xs text-gray-500">Total Late</p>
              <p class="text-lg font-bold text-primary-600">{{ termPayload!.totalLate }}</p>
            </div>
          </div>

          <div class="overflow-x-auto">
            <table class="w-full min-w-max border-collapse text-sm">
              <thead>
                <tr class="bg-gray-50">
                  <th class="border border-gray-200 p-2.5 text-left font-semibold">Teacher</th>
                  <th class="border border-gray-200 p-2.5 text-center font-semibold">Working Days</th>
                  <th class="border border-gray-200 p-2.5 text-center font-semibold">Present</th>
                  <th class="border border-gray-200 p-2.5 text-center font-semibold">Absent</th>
                  <th class="border border-gray-200 p-2.5 text-center font-semibold">Late</th>
                  <th class="border border-gray-200 p-2.5 text-center font-semibold">Attendance %</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="t in termPayload!.teachers" :key="t.teacherId">
                  <td class="border border-gray-200 p-2.5">{{ t.teacherName }}</td>
                  <td class="border border-gray-200 p-2.5 text-center">{{ t.workingDays }}</td>
                  <td class="border border-gray-200 p-2.5 text-center">{{ t.present }}</td>
                  <td class="border border-gray-200 p-2.5 text-center">{{ t.absent }}</td>
                  <td class="border border-gray-200 p-2.5 text-center">{{ t.late }}</td>
                  <td class="border border-gray-200 p-2.5 text-center font-semibold text-gray-700">
                    {{ t.attendancePercentage != null ? `${t.attendancePercentage}%` : '—' }}
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </template>
        <div class="mt-10 grid grid-cols-1 gap-8 text-sm sm:grid-cols-2">
          <div class="space-y-6">
            <div>
              <p class="border-b border-gray-400 pb-1">&nbsp;</p>
              <p class="mt-1 text-xs text-gray-500">Prepared by (Signature)</p>
            </div>
            <div>
              <p class="border-b border-gray-400 pb-1">&nbsp;</p>
              <p class="mt-1 text-xs text-gray-500">Name / Position</p>
            </div>
            <div>
              <p class="border-b border-gray-400 pb-1">&nbsp;</p>
              <p class="mt-1 text-xs text-gray-500">Date</p>
            </div>
          </div>
          <div class="flex items-end justify-center sm:justify-end">
            <div
              class="flex h-28 w-28 items-center justify-center rounded-full border-2 border-dashed border-gray-300 text-center text-[10px] text-gray-400">
              School Stamp
            </div>
          </div>
        </div>

        <p class="mt-8 text-center text-[10px] uppercase tracking-widest text-gray-300">
          Generated by Skultem &middot; Internal management document
        </p>
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
const termStore = useTermStore()
const teacherAttendanceStore = useTeacherAttendanceStore()
const { school } = useSchoolInfo()
const { success, error: toastError } = useNotify()

const reportTypes: { label: string, value: TeacherManagementReportType }[] = [
  { label: 'Daily Teacher Attendance Report', value: 'DAILY_REGISTER' },
  { label: 'Monthly Teacher Attendance Report', value: 'MONTHLY_SUMMARY' },
  { label: 'Term Teacher Attendance Report', value: 'TERM_SUMMARY' }
]

const form = reactive({
  reportType: 'DAILY_REGISTER' as TeacherManagementReportType,
  termId: '',
  date: new Date().toISOString().split('T')[0] as string,
  month: new Date().toISOString().slice(0, 7)
})

const generating = ref(false)
const downloading = ref(false)
// The data: URI logo (safe for the PDF capture) of the viewer's own section, if they're limited to
// one; the school's plain logo shows meanwhile.
const { logoSrc: reportLogo, loadLogo, ready: logoReady } = useReportLogo()
const logoSrc = computed(() => reportLogo.value || school.value?.logo || '')

const terms = computed(() => termStore.records.map(t => ({ label: t.name, value: t.id })))

const report = computed(() => teacherAttendanceStore.managementReport)
const dailyPayload = computed(() => report.value?.reportType === 'DAILY_REGISTER' ? report.value.payload as TeacherAttendanceRoster : null)
const monthlyPayload = computed(() => report.value?.reportType === 'MONTHLY_SUMMARY' ? report.value.payload as TeacherAttendanceSummaryRow[] : [])
const termPayload = computed(() => report.value?.reportType === 'TERM_SUMMARY' ? report.value.payload as TermTeacherAttendanceSummary : null)

const isEmptyReport = computed(() => {
  if (!report.value) return false
  if (dailyPayload.value) return dailyPayload.value.totalCount === 0
  if (report.value.reportType === 'MONTHLY_SUMMARY') return monthlyPayload.value.length === 0
  if (termPayload.value) return termPayload.value.teachers.length === 0
  return false
})

const canGenerate = computed(() => {
  if (form.reportType === 'DAILY_REGISTER') return !!form.date
  if (form.reportType === 'MONTHLY_SUMMARY') return !!form.month
  return !!form.termId
})

const termLabel = computed(() => terms.value.find(t => t.value === form.termId)?.label || '—')
const periodLabel = computed(() => {
  if (form.reportType === 'DAILY_REGISTER') {
    return form.date ? new Date(form.date).toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' }) : '—'
  }
  if (form.reportType === 'MONTHLY_SUMMARY') {
    const [year, month] = form.month.split('-').map(Number)
    return year && month ? new Date(year, month - 1, 1).toLocaleDateString(undefined, { year: 'numeric', month: 'long' }) : '—'
  }
  return termLabel.value
})
const generatedDate = computed(() => new Date().toLocaleDateString())
const schoolName = computed(() => school.value?.name || 'Skultem')

function teacherName(teacher: Teacher) {
  return `${teacher.user?.givenNames || ''} ${teacher.user?.familyName || ''}`.trim()
}

function sanitizeFilename(value: string) {
  return String(value).replace(/[^a-z0-9-_]/gi, '-')
}

async function generate() {
  if (!canGenerate.value) return
  generating.value = true
  try {
    const [year, month] = form.month.split('-').map(Number)
    await teacherAttendanceStore.fetchManagementReport({
      reportType: form.reportType,
      termId: form.reportType === 'TERM_SUMMARY' ? form.termId : undefined,
      date: form.reportType === 'DAILY_REGISTER' ? form.date : undefined,
      year: form.reportType === 'MONTHLY_SUMMARY' ? year : undefined,
      month: form.reportType === 'MONTHLY_SUMMARY' ? month : undefined
    })
  } catch (err: any) {
    toastError(err?.message || 'Failed to generate report')
  } finally {
    generating.value = false
  }
}

function printReport() {
  window.print()
}

async function downloadPdf() {
  if (!report.value) return
  downloading.value = true
  try {
    await logoReady() // the print-safe logo must be in before the PDF is drawn
    const { $generatePdf } = useNuxtApp()
    await $generatePdf('#teacher-management-report-preview', `teacher-management-report-${sanitizeFilename(form.reportType)}`)
    success('Report downloaded')
  } catch (err: any) {
    toastError(err?.message || 'Failed to generate PDF')
  } finally {
    downloading.value = false
  }
}

onMounted(async () => {
  loadLogo() // not awaited - fetches in the background
  useAppStore().setTitle('Human Resource')
  useAppStore().setBack('/hr')
  document.title = 'Management Reports | HR | Skultem'

  await termStore.fetchAll(1, 100)
  const active = await termStore.getActive()
  form.termId = active?.id || ''
})

definePageMeta({
  role: [Role.ADMIN, Role.OWNER, Role.PROPRIETOR]
})
</script>
