<template>
  <div class="space-y-4 px-4 md:px-6">
    <Heading title="Monthly Summary" subtitle="Staff attendance performance for every teacher over a month.">
      <UButton icon="i-lucide-download" color="primary" class="justify-center" :loading="downloading"
        :disabled="!summary.length" @click="downloadPdf">
        Export PDF
      </UButton>
    </Heading>

    <HrSectionNav />

    <UCard>
      <div class="grid gap-4 sm:grid-cols-2">
        <UFormField label="Month">
          <UInput v-model="filters.month" type="month" class="w-full" />
        </UFormField>
        <UFormField label="Teacher (optional)">
          <UInput v-model="search" icon="i-lucide-search" placeholder="Search teacher..." class="w-full" />
        </UFormField>
      </div>
    </UCard>

    <UCard v-if="loading">
      <div class="space-y-3">
        <USkeleton class="h-8 w-64" />
        <USkeleton v-for="i in 6" :key="i" class="h-8 w-full" />
      </div>
    </UCard>

    <UCard v-else-if="!filteredSummary.length">
      <div class="flex flex-col items-center justify-center py-14 text-center">
        <UIcon name="i-lucide-calendar-x" class="mb-3 size-10 text-muted" />
        <p class="text-sm font-medium text-highlighted">No attendance records found for this period.</p>
      </div>
    </UCard>

    <template v-else>
      <div id="teacher-monthly-summary-preview" class="rounded-lg bg-white text-gray-900 px-2">
        <div class="mb-4 border-b-4 border-primary-500 pb-5 pt-6 text-center sm:pt-8">
          <img v-if="logoSrc" :src="logoSrc" class="mx-auto size-40 object-contain" alt="School logo">
          <h2 class="text-xl font-black tracking-wide">{{ schoolName }}</h2>
          <p class="mt-1 text-sm font-semibold text-gray-600">Staff Monthly Attendance Summary</p>
          <div class="mt-3 flex flex-wrap items-center justify-center gap-x-4 gap-y-1 text-xs text-gray-500">
            <span>Month: {{ monthLabel }}</span>
          </div>
        </div>

        <div class="overflow-x-auto">
          <table class="w-full min-w-max border-collapse text-sm">
            <thead>
              <tr class="bg-gray-50">
                <th class="border border-gray-200 p-2.5 text-left font-semibold">Teacher</th>
                <th class="border border-gray-200 p-2.5 text-center font-semibold">Working Days</th>
                <th class="border border-gray-200 p-2.5 text-center font-semibold">Present</th>
                <th class="border border-gray-200 p-2.5 text-center font-semibold">Absent</th>
                <th class="border border-gray-200 p-2.5 text-center font-semibold">Late</th>
                <th class="border border-gray-200 p-2.5 text-center font-semibold">Attendance %</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="t in filteredSummary" :key="t.teacherId">
                <td class="border border-gray-200 p-2.5">{{ t.teacherName }}</td>
                <td class="border border-gray-200 p-2.5 text-center">{{ t.workingDays }}</td>
                <td class="border border-gray-200 p-2.5 text-center">{{ t.present }}</td>
                <td class="border border-gray-200 p-2.5 text-center">{{ t.absent }}</td>
                <td class="border border-gray-200 p-2.5 text-center">{{ t.late }}</td>
                <td class="border border-gray-200 p-2.5 text-center font-semibold text-gray-700">
                  {{ t.attendancePercentage != null ? `${t.attendancePercentage}%` : '—' }}
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <p class="mt-6 text-center text-[10px] uppercase tracking-widest text-gray-300">
          Generated by Skultem &middot; {{ generatedDate }}
        </p>
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
const teacherAttendanceStore = useTeacherAttendanceStore()
const { school } = useSchoolInfo()

const filters = reactive({
  month: currentMonthISO()
})

const search = ref('')
const downloading = ref(false)
const { success, error: toastError } = useNotify()

const summary = computed(() => teacherAttendanceStore.monthlySummary)
const loading = computed(() => teacherAttendanceStore.loadingMonthlySummary)

const filteredSummary = computed(() => {
  if (!search.value.trim()) return summary.value

  const query = search.value.trim().toLowerCase()
  return summary.value.filter(t => t.teacherName.toLowerCase().includes(query))
})

const monthLabel = computed(() => {
  if (!filters.month) return '—'
  const [year, month] = filters.month.split('-').map(Number)
  return new Date(year!, (month || 1) - 1, 1).toLocaleDateString(undefined, { year: 'numeric', month: 'long' })
})
const generatedDate = computed(() => new Date().toLocaleDateString())
const schoolName = computed(() => school.value?.name || 'Skultem')
// The data: URI logo (safe for the PDF capture) of the viewer's own section, if they're limited to
// one; the school's plain logo shows meanwhile.
const { logoSrc: reportLogo, loadLogo, ready: logoReady } = useReportLogo()
const logoSrc = computed(() => reportLogo.value || school.value?.logo || '')

function currentMonthISO() {
  return new Date().toISOString().slice(0, 7)
}

function sanitizeFilename(value: string) {
  return String(value).replace(/[^a-z0-9-_]/gi, '-')
}

async function loadSummary() {
  const [year, month] = filters.month.split('-').map(Number)
  if (!year || !month) return
  await teacherAttendanceStore.fetchMonthlySummary(year, month)
}

async function downloadPdf() {
  if (!summary.value.length) return
  downloading.value = true
  try {
    await logoReady() // the print-safe logo must be in before the PDF is drawn
    const { $generatePdf } = useNuxtApp()
    await $generatePdf('#teacher-monthly-summary-preview', `teacher-monthly-summary-${sanitizeFilename(filters.month)}`)
    success('Summary downloaded')
  } catch (err: any) {
    toastError(err?.message || 'Failed to generate PDF')
  } finally {
    downloading.value = false
  }
}

watch(() => filters.month, loadSummary)

onMounted(async () => {
  loadLogo() // not awaited - fetches in the background
  useAppStore().setTitle('Human Resource')
  useAppStore().setBack('/hr')
  document.title = 'Monthly Summary | HR | Skultem'

  await loadSummary()
})

definePageMeta({
  role: [Role.ADMIN, Role.OWNER, Role.PROPRIETOR]
})
</script>
