<template>
  <div class="space-y-4 px-4 md:px-6">
    <Heading title="Student Demographics" subtitle="Gender and religion breakdown for management reporting.">
      <div class="flex flex-wrap gap-2">
        <UButton icon="i-lucide-printer" variant="soft" @click="() => window.print()">Print</UButton>
        <UButton icon="i-lucide-download" color="primary" variant="soft" :loading="downloading" @click="downloadPdf">
          Export PDF
        </UButton>
      </div>
    </Heading>

    <UCard>
      <div class="grid gap-4 sm:grid-cols-2">
        <UFormField label="Class">
          <USelectMenu v-model="filters.classId" :items="classes" :loading="classStore.loading" value-key="value"
            label-key="label" placeholder="All classes" class="w-full" />
        </UFormField>

        <UFormField label="Level">
          <USelectMenu v-model="filters.level" :items="levels" value-key="value" label-key="label"
            placeholder="All levels" class="w-full" />
        </UFormField>
      </div>
    </UCard>

    <UCard v-if="loading">
      <div class="space-y-3">
        <USkeleton class="h-8 w-64" />
        <USkeleton v-for="i in 3" :key="i" class="h-8 w-full" />
      </div>
    </UCard>

    <div v-else-if="demographics" id="demographics-preview" class="space-y-4 rounded-lg bg-white p-2 text-gray-900">
      <div class="mb-4 border-b-4 border-primary-500 px-6 pb-5 pt-6 text-center sm:px-8 sm:pt-8">
        <img v-if="logoSrc" :src="logoSrc" class="mx-auto size-16 object-contain" alt="School logo">
        <h2 class="text-xl font-black tracking-wide">{{ schoolName }}</h2>
        <p class="mt-1 text-sm font-semibold text-gray-600">Student Demographics</p>
        <div class="mt-3 flex flex-wrap items-center justify-center gap-x-4 gap-y-1 text-xs text-gray-500">
          <span v-if="classLabel">Class: {{ classLabel }}</span>
          <span v-if="filters.level">Level: {{ filters.level }}</span>
        </div>
      </div>

      <div class="grid grid-cols-2 gap-4 px-2 sm:grid-cols-4">
        <div class="rounded-xl bg-primary-50 p-3 text-center">
          <p class="text-xs text-gray-500">Total Students</p>
          <p class="text-xl font-bold text-primary-600">{{ demographics.totalStudents }}</p>
        </div>
        <div class="rounded-xl bg-primary-50 p-3 text-center">
          <p class="text-xs text-gray-500">Boys</p>
          <p class="text-xl font-bold text-primary-600">{{ demographics.boys }}</p>
        </div>
        <div class="rounded-xl bg-primary-50 p-3 text-center">
          <p class="text-xs text-gray-500">Girls</p>
          <p class="text-xl font-bold text-primary-600">{{ demographics.girls }}</p>
        </div>
        <div class="rounded-xl bg-primary-50 p-3 text-center">
          <p class="text-xs text-gray-500">Not Specified</p>
          <p class="text-xl font-bold text-primary-600">{{ demographics.genderNotSpecified }}</p>
        </div>
      </div>

      <div class="grid gap-4 px-2 lg:grid-cols-2">
        <div class="rounded-lg border border-gray-200 bg-white">
          <div class="border-b border-gray-200 px-4 py-3">
            <h2 class="font-semibold text-gray-900">Gender</h2>
          </div>
          <div class="p-4">
            <ClientOnly>
              <ApexChart type="donut" height="280" :options="genderChartOptions" :series="genderChartSeries" />
            </ClientOnly>
          </div>
        </div>

        <div class="rounded-lg border border-gray-200 bg-white">
          <div class="border-b border-gray-200 px-4 py-3">
            <h2 class="font-semibold text-gray-900">Religion</h2>
          </div>
          <div class="p-4">
            <ClientOnly>
              <ApexChart type="bar" height="280" :options="religionChartOptions" :series="religionChartSeries" />
            </ClientOnly>
          </div>
        </div>
      </div>

      <p class="px-2 text-center text-[10px] uppercase tracking-widest text-gray-300">
        Generated by Skultem &middot; {{ generatedDate }}
      </p>
    </div>
  </div>
</template>

<script setup lang="ts">
const ApexChart = defineAsyncComponent(() => import('vue3-apexcharts'))

const classStore = useClassStore()
const reportStore = useAcademicReportStore()
const { school } = useSchoolInfo()
const { success, error: toastError } = useNotify()

const { demographics, loadingDemographics: loading } = storeToRefs(reportStore)

const filters = reactive({
  classId: '',
  level: ''
})

const downloading = ref(false)
const logoSrc = ref('')

const classes = computed(() => classStore.records.map(c => ({ label: c.name, value: c.id })))
const classLabel = computed(() => classes.value.find(c => c.value === filters.classId)?.label || '')
// Backend Level enum is uppercase (PRIMARY/JSS/SSS) - kept local to this filter rather than reusing
// the app-wide Level enum, whose values are mixed-case for display elsewhere.
const levels = [
  { label: 'Primary', value: 'PRIMARY' },
  { label: 'JSS', value: 'JSS' },
  { label: 'SSS', value: 'SSS' }
]

const schoolName = computed(() => school.value?.name || 'Skultem')
const generatedDate = computed(() => new Date().toLocaleString())

const genderChartOptions = computed(() => ({
  chart: { id: 'demographics-gender' },
  labels: ['Boys', 'Girls', 'Not specified'],
  colors: ['#3b82f6', '#ec4899', '#94a3b8'],
  legend: { position: 'bottom' },
  dataLabels: { enabled: true }
}))

const genderChartSeries = computed(() => demographics.value
  ? [demographics.value.boys, demographics.value.girls, demographics.value.genderNotSpecified]
  : [])

const religionChartOptions = computed(() => ({
  chart: { id: 'demographics-religion', toolbar: { show: false } },
  xaxis: { categories: demographics.value?.religions.map(r => r.label) || [] },
  colors: ['#7b2183'],
  grid: { borderColor: 'var(--app-border)', strokeDashArray: 4 },
  dataLabels: { enabled: true }
}))

const religionChartSeries = computed(() => [{
  name: 'Students',
  data: demographics.value?.religions.map(r => r.count) || []
}])

async function loadDemographics() {
  await reportStore.fetchDemographics({
    classId: filters.classId || undefined,
    level: filters.level || undefined
  })
}

watch(() => [filters.classId, filters.level], loadDemographics)

async function downloadPdf() {
  downloading.value = true
  try {
    const { $generatePdf } = useNuxtApp()
    await $generatePdf('#demographics-preview', 'student-demographics')
    success('Report downloaded')
  } catch (err: any) {
    toastError(err?.message || 'Failed to generate PDF')
  } finally {
    downloading.value = false
  }
}

onMounted(async () => {
  useAppStore().setTitle('Student Demographics')
  document.title = 'Student Demographics | Skultem'

  await classStore.fetchAll(1, 200)
  await loadDemographics()

  const assets = await SchoolApi().getBrandingAssets()
  logoSrc.value = assets?.logo || school.value?.logo || ''
})

definePageMeta({
  role: [Role.ADMIN, Role.OWNER, Role.PROPRIETOR]
})
</script>
