<template>
  <div class="space-y-4 px-4 md:px-6">
    <FeeReportSectionNav />

    <Heading title="Daily Collection" subtitle="What was collected on a day, or across a date range, by payment method.">
      <div class="flex gap-2">
        <UButton icon="i-lucide-download" variant="outline" color="neutral" class="justify-center"
          :loading="exportingCsv" @click="exportTransactions">
          Export CSV
        </UButton>
        <UButton icon="i-lucide-download" color="primary" class="justify-center" :loading="downloading"
          :disabled="!report" @click="downloadPdf">
          Export PDF
        </UButton>
      </div>
    </Heading>

    <UCard>
      <div class="grid gap-4 sm:grid-cols-2">
        <UFormField label="From">
          <UInput v-model="filters.from" type="date" class="w-full" />
        </UFormField>
        <UFormField label="To">
          <UInput v-model="filters.to" type="date" class="w-full" />
        </UFormField>
      </div>
    </UCard>

    <UCard v-if="loading">
      <div class="space-y-3">
        <USkeleton class="h-8 w-64" />
        <USkeleton v-for="i in 4" :key="i" class="h-8 w-full" />
      </div>
    </UCard>

    <template v-else-if="report">
      <div id="daily-collection-preview" class="rounded-lg bg-white text-gray-900 px-2">
        <div class="mb-4 border-b-4 border-primary-500 pb-5 pt-6 text-center sm:pt-8">
          <img v-if="logoSrc" :src="logoSrc" class="mx-auto size-40 object-contain" alt="School logo">
          <h2 class="text-xl font-black tracking-wide">{{ schoolName }}</h2>
          <p class="mt-1 text-sm font-semibold text-gray-600">Daily Collection Report</p>
          <div class="mt-3 flex flex-wrap items-center justify-center gap-x-4 gap-y-1 text-xs text-gray-500">
            <span>{{ report.from === report.to ? report.from : `${report.from} — ${report.to}` }}</span>
          </div>
        </div>

        <div class="mb-6 grid grid-cols-2 gap-3">
          <div class="rounded-xl bg-primary-50 p-3 text-center">
            <p class="text-xs text-gray-500">Total Collected</p>
            <p class="text-lg font-bold text-primary-600">{{ format(report.totalCollected) }}</p>
          </div>
          <div class="rounded-xl bg-primary-50 p-3 text-center">
            <p class="text-xs text-gray-500">Payments</p>
            <p class="text-lg font-bold text-primary-600">{{ report.paymentCount }}</p>
          </div>
        </div>

        <p class="mb-2 text-sm font-semibold text-gray-700">By Payment Method</p>
        <div class="mb-6 overflow-x-auto">
          <table class="w-full min-w-max border-collapse text-sm">
            <thead>
              <tr class="bg-gray-50">
                <th class="border border-gray-200 p-2.5 text-left font-semibold">Method</th>
                <th class="border border-gray-200 p-2.5 text-right font-semibold">Amount</th>
                <th class="border border-gray-200 p-2.5 text-center font-semibold">Transactions</th>
                <th class="border border-gray-200 p-2.5 text-center font-semibold">% of Total</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="m in report.byMethod" :key="m.method">
                <td class="border border-gray-200 p-2.5">{{ parsePaymentMethod[m.method] || m.method }}</td>
                <td class="border border-gray-200 p-2.5 text-right font-semibold">{{ format(m.amount) }}</td>
                <td class="border border-gray-200 p-2.5 text-center">{{ m.transactionCount }}</td>
                <td class="border border-gray-200 p-2.5 text-center">{{ m.percentage }}%</td>
              </tr>
            </tbody>
            <tfoot v-if="report.byMethod.length">
              <tr class="bg-gray-50 font-semibold">
                <td class="border border-gray-200 p-2.5">Total</td>
                <td class="border border-gray-200 p-2.5 text-right">{{ format(report.totalCollected) }}</td>
                <td class="border border-gray-200 p-2.5 text-center">{{ report.paymentCount }}</td>
                <td class="border border-gray-200 p-2.5 text-center">100%</td>
              </tr>
            </tfoot>
          </table>
        </div>

        <p class="mt-6 text-center text-[10px] uppercase tracking-widest text-gray-300">
          Generated by Skultem &middot; {{ generatedDate }}
        </p>
      </div>
    </template>

    <UCard v-else>
      <div class="flex flex-col items-center justify-center py-14 text-center">
        <UIcon name="i-lucide-banknote" class="mb-3 size-10 text-muted" />
        <p class="text-sm font-medium text-highlighted">No payments collected in this period.</p>
      </div>
    </UCard>

    <!-- Transactions -->
    <UCard :ui="{ body: 'p-0 sm:p-0' }">
      <template #header>
        <p class="p-4 pb-0 font-semibold">Transactions</p>
      </template>
      <UTable class="hidden md:block" :columns="txColumns" :data="transactions" :loading="loading">
        <template #empty-state>
          <div class="flex flex-col items-center gap-2 py-10">
            <UIcon name="ph:books-light" class="text-4xl text-gray-400" />
            <p class="text-gray-500">No transactions found.</p>
          </div>
        </template>
        <template #loading>
          <TableLoading :size="txColumns.length" />
        </template>
        <template #paidAt-cell="{ row }">
          {{ new Date(row.original.paidAt).toLocaleString() }}
        </template>
        <template #amount-cell="{ row }">
          {{ format(row.original.amount) }}
        </template>
        <template #method-cell="{ row }">
          <UBadge :label="parsePaymentMethod[row.original.method] || row.original.method" variant="outline" />
        </template>
      </UTable>
      <div class="p-4 space-y-3 md:hidden">
        <template v-if="transactions.length">
          <div v-for="t in transactions" :key="t.id" class="rounded-xl border border-default p-3">
            <div class="flex items-start justify-between gap-2">
              <div class="min-w-0">
                <p class="truncate font-semibold text-highlighted">{{ t.studentName }}</p>
                <p class="text-xs text-muted">{{ t.className }} &middot; {{ t.feeCategoryName }}</p>
              </div>
              <p class="font-semibold text-success">{{ format(t.amount) }}</p>
            </div>
            <p class="mt-1 text-xs text-muted">{{ new Date(t.paidAt).toLocaleString() }} &middot; {{ parsePaymentMethod[t.method] || t.method }}</p>
          </div>
        </template>
        <template v-else>
          <div class="flex flex-col items-center justify-center py-14">
            <UIcon name="ph:books-light" class="mb-3 text-4xl text-gray-400" />
            <p class="text-sm text-gray-500">No transactions found.</p>
          </div>
        </template>
      </div>
      <template #footer>
        <div class="flex justify-between items-center flex-col md:flex-row space-y-2 md:space-y-0">
          <Showing :meta="meta" />
          <UPagination v-model:page="page" size="sm" :page-size="meta.size" :items-per-page="meta.size"
            :total="meta.total" show-edges />
        </div>
      </template>
    </UCard>
  </div>
</template>

<script setup lang="ts">
const route = useRoute()
const router = useRouter()

const store = useFeeReportStore()
const { school } = useSchoolInfo()
const { format } = useMoney()
const { success, error: toastError } = useNotify()

function today() {
  return new Date().toISOString().slice(0, 10)
}

const filters = reactive({
  from: today(),
  to: today(),
})

const downloading = ref(false)
const exportingCsv = ref(false)

const txColumns = [
  { accessorKey: 'paidAt', header: 'Date' },
  { accessorKey: 'receiptNo', header: 'Receipt' },
  { accessorKey: 'studentName', header: 'Student' },
  { accessorKey: 'className', header: 'Class' },
  { accessorKey: 'amount', header: 'Amount' },
  { accessorKey: 'method', header: 'Method' },
  { accessorKey: 'recordedBy', header: 'Recorded By' },
]

const report = computed(() => store.dailyCollection)
const transactions = computed(() => store.paymentHistory)
const meta = computed(() => store.paymentHistoryMeta)
const loading = computed(() => store.loading)

const generatedDate = computed(() => new Date().toLocaleDateString())
const schoolName = computed(() => school.value?.name || 'Skultem')
const { logoSrc, loadLogo, ready: logoReady } = useReportLogo()

const page = computed<number>({
  get: () => Number(route.query.page ?? 1),
  set: (value) => updateQuery({ page: value }),
})
const size = ref(runtimeConf().limit)

function updateQuery(newQuery: Record<string, any>) {
  router.replace({ query: { ...route.query, ...newQuery } })
}

async function loadReport() {
  await store.fetchDailyCollection(filters.from || undefined, filters.to || undefined)
}

async function loadTransactions() {
  await store.fetchPaymentHistory(page.value, size.value, {
    from: filters.from || undefined,
    to: filters.to || undefined,
  })
}

async function downloadPdf() {
  if (!report.value) return
  downloading.value = true
  try {
    await logoReady() // the print-safe logo must be in before the PDF is drawn
    const { $generatePdf } = useNuxtApp()
    await $generatePdf('#daily-collection-preview', `daily-collection-${filters.from}-${filters.to}`)
    success('Report downloaded')
  } catch (err: any) {
    toastError(err?.message || 'Failed to generate PDF')
  } finally {
    downloading.value = false
  }
}

async function exportTransactions() {
  exportingCsv.value = true
  try {
    const { blob, filename } = await ReportApi().exportFeePaymentHistory('csv', {
      from: filters.from || undefined,
      to: filters.to || undefined,
    })
    downloadBlob(blob, filename)
    success('Transactions downloaded')
  } catch (err: any) {
    toastError(err?.message || 'Failed to export transactions')
  } finally {
    exportingCsv.value = false
  }
}

watch(() => [filters.from, filters.to], () => {
  updateQuery({ page: 1 })
  loadReport()
  if (page.value === 1) loadTransactions()
})
watch(page, loadTransactions)

onMounted(async () => {
  loadLogo() // not awaited - fetches in the background, doesn't block the report's own data

  useAppStore().setTitle('Daily Collection')
  document.title = 'Daily Collection | Skultem'

  if (!route.query.page || !route.query.size) {
    updateQuery({ page: page.value })
  }

  await loadReport()
  await loadTransactions()
})

definePageMeta({
  role: [Role.ACCOUNTANT, Role.PROPRIETOR, Role.OWNER]
})
</script>
