<template>
  <div class="space-y-4 px-4 md:px-6">
    <FeeReportSectionNav />

    <Heading title="Fees Dashboard" subtitle="The school's current fee position for the selected academic year and term.">
      <UButton icon="i-lucide-download" color="primary" class="justify-center" :loading="downloading"
        :disabled="!dashboard" @click="downloadPdf">
        Export PDF
      </UButton>
    </Heading>

    <UCard>
      <div class="grid gap-4 sm:grid-cols-2">
        <UFormField label="Academic Year">
          <USelectMenu v-model="filters.academicYearId" :items="academicYears" value-key="value" label-key="label"
            placeholder="Active year" class="w-full" />
        </UFormField>

        <UFormField label="Term">
          <USelectMenu v-model="filters.termId" :items="terms" value-key="value" label-key="label" clear
            placeholder="Whole year" class="w-full" />
        </UFormField>
      </div>
    </UCard>

    <UCard v-if="loading">
      <div class="grid grid-cols-2 gap-4 sm:grid-cols-4">
        <USkeleton v-for="i in 8" :key="i" class="h-24 w-full" />
      </div>
    </UCard>

    <template v-else-if="dashboard">
      <div id="fees-dashboard-preview" class="rounded-lg bg-white text-gray-900 px-2">
        <div class="mb-4 border-b-4 border-primary-500 pb-5 pt-6 text-center sm:pt-8">
          <img v-if="logoSrc" :src="logoSrc" class="mx-auto size-40 object-contain" alt="School logo">
          <h2 class="text-xl font-black tracking-wide">{{ schoolName }}</h2>
          <p class="mt-1 text-sm font-semibold text-gray-600">Fees Dashboard</p>
          <div class="mt-3 flex flex-wrap items-center justify-center gap-x-4 gap-y-1 text-xs text-gray-500">
            <span>Academic Year: {{ dashboard.academicYearName }}</span>
            <span v-if="dashboard.termName">Term: {{ dashboard.termName }}</span>
          </div>
        </div>

        <div class="grid grid-cols-2 gap-4 sm:grid-cols-4">
          <Metric :record="{ label: 'Total Expected', value: format(dashboard.totalExpected), icon: 'i-lucide-banknote', color: 'info', isReady: true }" />
          <Metric :record="{ label: 'Total Collected', value: format(dashboard.totalCollected), icon: 'i-lucide-check-circle', color: 'success', isReady: true }" />
          <Metric :record="{ label: 'Outstanding', value: format(dashboard.totalOutstanding), icon: 'i-lucide-alert-triangle', color: 'error', isReady: true }" />
          <Metric :record="{ label: 'Collection Rate', value: `${dashboard.collectionRate}%`, icon: 'i-lucide-percent', color: 'primary', isReady: true }" />
          <Metric :record="{ label: 'Fully Paid Students', value: String(dashboard.studentsFullyPaid), icon: 'i-lucide-user-check', color: 'success', isReady: true }" />
          <Metric :record="{ label: 'Students With Balance', value: String(dashboard.studentsWithBalance), icon: 'i-lucide-user-minus', color: 'warning', isReady: true }" />
          <Metric :record="{ label: 'Students With No Payment', value: String(dashboard.studentsNoPayment), icon: 'i-lucide-user-x', color: 'error', isReady: true }" />
          <Metric :record="{ label: 'Total Students', value: String(dashboard.totalStudents), icon: 'i-lucide-users', color: 'neutral', isReady: true }" />
        </div>

        <FeeReportInsightSection class="mt-6" title="Key Insights" :items="insights" />

        <p class="mt-6 text-center text-[10px] uppercase tracking-widest text-gray-300">
          Generated by Skultem &middot; {{ generatedDate }}
        </p>
      </div>
    </template>

    <UCard v-else>
      <div class="flex flex-col items-center justify-center py-14 text-center">
        <UIcon name="i-lucide-banknote" class="mb-3 size-10 text-muted" />
        <p class="text-sm font-medium text-highlighted">No fee data found for this period.</p>
      </div>
    </UCard>
  </div>
</template>

<script setup lang="ts">
const academicYearStore = useAcademicYearStore()
const termStore = useTermStore()
const store = useFeeReportStore()
const { school } = useSchoolInfo()
const { format } = useMoney()
const { success, error: toastError } = useNotify()

const filters = reactive({
  academicYearId: '',
  termId: '',
})

const downloading = ref(false)

const academicYears = computed(() => academicYearStore.list)
const terms = computed(() => termStore.records.map(t => ({ label: t.name, value: t.id })))

const dashboard = computed(() => store.dashboard)
const loading = computed(() => store.loading)

const schoolName = computed(() => school.value?.name || 'Skultem')
const { logoSrc, loadLogo, ready: logoReady } = useReportLogo()
const generatedDate = computed(() => new Date().toLocaleDateString())

// Plain frontend derivations of the numbers already on the page - same approach as the academic
// reports "What needs your attention" section. Only shown when there's real data behind them.
const insights = computed(() => {
  const d = dashboard.value
  if (!d) return []
  const list: { text: string; color: string }[] = []

  if (d.totalExpected > 0) {
    list.push({
      text: `${d.collectionRate}% of expected fees have been collected this ${d.termName ? 'term' : 'year'}.`,
      color: d.collectionRate >= 75 ? 'success' : d.collectionRate >= 40 ? 'warning' : 'error',
    })
  }
  if (d.studentsWithBalance > 0) {
    list.push({
      text: `${d.studentsWithBalance} student${d.studentsWithBalance === 1 ? '' : 's'} ${d.studentsWithBalance === 1 ? 'has' : 'have'} made a partial payment and still owe a balance.`,
      color: 'warning',
    })
  }
  if (d.studentsNoPayment > 0) {
    list.push({
      text: `${d.studentsNoPayment} student${d.studentsNoPayment === 1 ? '' : 's'} ${d.studentsNoPayment === 1 ? 'has' : 'have'} made no payment at all yet.`,
      color: 'error',
    })
  }
  if (d.totalStudents > 0 && d.studentsWithBalance === 0 && d.studentsNoPayment === 0) {
    list.push({
      text: 'Every student with a fee obligation has paid in full for this period.',
      color: 'success',
    })
  }
  return list
})

function sanitizeFilename(value: string) {
  return String(value).replace(/[^a-z0-9-_]/gi, '-')
}

async function loadDashboard() {
  await store.fetchDashboard(filters.academicYearId || undefined, filters.termId || undefined)
}

async function downloadPdf() {
  if (!dashboard.value) return
  downloading.value = true
  try {
    await logoReady() // the print-safe logo must be in before the PDF is drawn
    const { $generatePdf } = useNuxtApp()
    await $generatePdf('#fees-dashboard-preview', `fees-dashboard-${sanitizeFilename(dashboard.value.academicYearName)}`)
    success('Dashboard downloaded')
  } catch (err: any) {
    toastError(err?.message || 'Failed to generate PDF')
  } finally {
    downloading.value = false
  }
}

watch(() => [filters.academicYearId, filters.termId], loadDashboard)

onMounted(async () => {
  loadLogo() // not awaited - fetches in the background, doesn't block the report's own data

  useAppStore().setTitle('Fees Dashboard')
  document.title = 'Fees Dashboard | Skultem'

  await academicYearStore.fetchAll(1, 100)
  filters.academicYearId = academicYearStore.viewingYearId || academicYearStore.activeYear?.id || ''

  await termStore.fetchAll(1, 100)

  await loadDashboard()
})

definePageMeta({
  role: [Role.ACCOUNTANT, Role.PROPRIETOR, Role.OWNER]
})
</script>
