<template>
  <div class="space-y-4 px-4 md:px-6">
    <FeeReportSectionNav />

    <Heading title="Payment Methods" subtitle="How the school's fees are being collected.">
      <UButton icon="i-lucide-download" color="primary" class="justify-center" :loading="downloading"
        :disabled="!summary" @click="downloadPdf">
        Export PDF
      </UButton>
    </Heading>

    <UCard>
      <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <UFormField label="Academic Year">
          <USelectMenu v-model="filters.academicYearId" :items="academicYears" value-key="value" label-key="label"
            :disabled="usingDateRange" placeholder="Active year" class="w-full" />
        </UFormField>
        <UFormField label="Term">
          <USelectMenu v-model="filters.termId" :items="terms" value-key="value" label-key="label" clear
            :disabled="usingDateRange" placeholder="Whole year" class="w-full" />
        </UFormField>
        <UFormField label="From">
          <UInput v-model="filters.from" type="date" class="w-full" />
        </UFormField>
        <UFormField label="To">
          <UInput v-model="filters.to" type="date" class="w-full" />
        </UFormField>
      </div>
    </UCard>

    <UCard v-if="loading">
      <div class="space-y-3">
        <USkeleton class="h-8 w-64" />
        <USkeleton v-for="i in 4" :key="i" class="h-8 w-full" />
      </div>
    </UCard>

    <template v-else-if="summary && summary.methods.length">
      <div id="payment-methods-preview" class="rounded-lg bg-white text-gray-900 px-2">
        <div class="mb-4 border-b-4 border-primary-500 pb-5 pt-6 text-center sm:pt-8">
          <img v-if="logoSrc" :src="logoSrc" class="mx-auto size-40 object-contain" alt="School logo">
          <h2 class="text-xl font-black tracking-wide">{{ schoolName }}</h2>
          <p class="mt-1 text-sm font-semibold text-gray-600">Payment Method Summary</p>
        </div>

        <div class="mb-6 rounded-xl bg-primary-50 p-3 text-center">
          <p class="text-xs text-gray-500">Total Collected</p>
          <p class="text-lg font-bold text-primary-600">{{ format(summary.totalCollected) }}</p>
        </div>

        <FeeReportInsightSection title="Key Insights"
          :items="insight ? [{ text: insight, color: 'info' }] : []" />

        <div class="overflow-x-auto">
          <table class="w-full min-w-max border-collapse text-sm">
            <thead>
              <tr class="bg-gray-50">
                <th class="border border-gray-200 p-2.5 text-left font-semibold">Method</th>
                <th class="border border-gray-200 p-2.5 text-right font-semibold">Amount</th>
                <th class="border border-gray-200 p-2.5 text-center font-semibold">Transactions</th>
                <th class="border border-gray-200 p-2.5 text-center font-semibold">% of Total</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="m in summary.methods" :key="m.method">
                <td class="border border-gray-200 p-2.5">{{ parsePaymentMethod[m.method] || m.method }}</td>
                <td class="border border-gray-200 p-2.5 text-right font-semibold">{{ format(m.amount) }}</td>
                <td class="border border-gray-200 p-2.5 text-center">{{ m.transactionCount }}</td>
                <td class="border border-gray-200 p-2.5 text-center">{{ m.percentage }}%</td>
              </tr>
            </tbody>
          </table>
        </div>

        <p class="mt-6 text-center text-[10px] uppercase tracking-widest text-gray-300">
          Generated by Skultem &middot; {{ generatedDate }}
        </p>
      </div>
    </template>

    <UCard v-else>
      <div class="flex flex-col items-center justify-center py-14 text-center">
        <UIcon name="i-lucide-wallet" class="mb-3 size-10 text-muted" />
        <p class="text-sm font-medium text-highlighted">No payments collected in this period.</p>
      </div>
    </UCard>
  </div>
</template>

<script setup lang="ts">
const academicYearStore = useAcademicYearStore()
const termStore = useTermStore()
const store = useFeeReportStore()
const { school } = useSchoolInfo()
const { format } = useMoney()
const { success, error: toastError } = useNotify()

const filters = reactive({
  academicYearId: '',
  termId: '',
  from: '',
  to: '',
})

const downloading = ref(false)

const academicYears = computed(() => academicYearStore.list)
const terms = computed(() => termStore.records.map(t => ({ label: t.name, value: t.id })))

// An explicit date range takes over from year/term (matches the backend's own precedence) - the
// year/term selects are disabled rather than hidden, so it's clear why they stopped applying.
const usingDateRange = computed(() => !!filters.from || !!filters.to)

const summary = computed(() => store.paymentMethods)
const loading = computed(() => store.loading)

const generatedDate = computed(() => new Date().toLocaleDateString())
const schoolName = computed(() => school.value?.name || 'Skultem')
const { logoSrc, loadLogo } = useReportLogo()

const insight = computed(() => {
  const s = summary.value
  if (!s || !s.methods.length) return ''
  const top = s.methods[0]
  return `${parsePaymentMethod[top.method] || top.method} represents ${top.percentage}% of total collections.`
})

function sanitizeFilename(value: string) {
  return String(value).replace(/[^a-z0-9-_]/gi, '-')
}

async function loadSummary() {
  await store.fetchPaymentMethods(filters.academicYearId || undefined, filters.termId || undefined,
    filters.from || undefined, filters.to || undefined)
}

async function downloadPdf() {
  if (!summary.value) return
  downloading.value = true
  try {
    const { $generatePdf } = useNuxtApp()
    await $generatePdf('#payment-methods-preview', 'payment-methods')
    success('Report downloaded')
  } catch (err: any) {
    toastError(err?.message || 'Failed to generate PDF')
  } finally {
    downloading.value = false
  }
}

watch(() => [filters.academicYearId, filters.termId, filters.from, filters.to], loadSummary)

onMounted(async () => {
  loadLogo() // not awaited - fetches in the background, doesn't block the report's own data

  useAppStore().setTitle('Payment Methods')
  document.title = 'Payment Methods | Skultem'

  await academicYearStore.fetchAll(1, 100)
  filters.academicYearId = academicYearStore.viewingYearId || academicYearStore.activeYear?.id || ''

  await termStore.fetchAll(1, 100)
  await loadSummary()
})

definePageMeta({
  role: [Role.ACCOUNTANT, Role.PROPRIETOR, Role.OWNER]
})
</script>
